"""
Title: Container With Most Water
Difficulty: Medium
Time: 5 min
URL: https://leetcode.com/problems/container-with-most-water/?envType=problem-list-v2&envId=two-pointers

You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.

Notice that you may not slant the container.

 

Example 1:

Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49
Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

Example 2:

Input: height = [1,1]
Output: 1

 

Constraints:

n == height.length

2 <= n <= 105

0 <= height[i] <= 104

Generated by CodeBridge
"""

class Solution:
    def maxArea(self, height: List[int]) -> int:
        leng = len(height)
        if leng < 2: return 0
        area = 0
        itr1 = 0
        itr2 = leng-1
        while itr1 < itr2:
            current_area = min(height[itr1], height[itr2]) * (itr2 - itr1)
            area = max(area, current_area)
            if height[itr1] < height[itr2]:
                itr1 += 1
            else:
                itr2 -= 1

        return area