"""
# Integer to Roman

**Difficulty:** Medium
**Tags:** Hash Table, Math, String
**URL:** https://leetcode.com/problems/integer-to-roman/

## Problem

Seven different symbols represent Roman numerals with the following values:


	
		
			Symbol
			Value
		
	
	
		
			I
			1
		
		
			V
			5
		
		
			X
			10
		
		
			L
			50
		
		
			C
			100
		
		
			D
			500
		
		
			M
			1000
		
	


Roman numerals are formed by appending&nbsp;the conversions of&nbsp;decimal place values&nbsp;from highest to lowest. Converting a decimal place value into a Roman numeral has the following rules:


	If the value does not start with 4 or&nbsp;9, select the symbol of the maximal value that can be subtracted from the input, append that symbol to the result, subtract its value, and convert the remainder to a Roman numeral.
	If the value starts with 4 or 9 use the&nbsp;subtractive form&nbsp;representing&nbsp;one symbol subtracted from the following symbol, for example,&nbsp;4 is 1 (I) less than 5 (V): IV&nbsp;and 9 is 1 (I) less than 10 (X): IX.&nbsp;Only the following subtractive forms are used: 4 (IV), 9 (IX),&nbsp;40 (XL), 90 (XC), 400 (CD) and 900 (CM).
	Only powers of 10 (I, X, C, M) can be appended consecutively at most 3 times to represent multiples of 10. You cannot append 5&nbsp;(V), 50 (L), or 500 (D) multiple times. If you need to append a symbol&nbsp;4 times&nbsp;use the subtractive form.


Given an integer, convert it to a Roman numeral.

&nbsp;
Example 1:


Input: num = 3749

Output: &quot;MMMDCCXLIX&quot;

Explanation:


3000 = MMM as 1000 (M) + 1000 (M) + 1000 (M)
 700 = DCC as 500 (D) + 100 (C) + 100 (C)
  40 = XL as 10 (X) less of 50 (L)
   9 = IX as 1 (I) less of 10 (X)
Note: 49 is not 1 (I) less of 50 (L) because the conversion is based on decimal places



Example 2:


Input: num = 58

Output: &quot;LVIII&quot;

Explanation:


50 = L
 8 = VIII



Example 3:


Input: num = 1994

Output: &quot;MCMXCIV&quot;

Explanation:


1000 = M
 900 = CM
  90 = XC
   4 = IV



&nbsp;
Constraints:


	1 &lt;= num &lt;= 3999

---
_Generated by CodeBridge_
"""

class Solution:
    def intToRoman(self, num: int) -> str:
        result = []
        predecessor = { 
            "V" : "I", 
            "X" : "I",
            "L" : "X", 
            "C" : "X",
            "D" : "C", 
            "M" : "C"
        }

        symbols = {
            1: "I",
            5: "V",
            10: "X",
            50: "L",
            100: "C",
            500: "D",
            1000: "M"
        }

        if num in symbols:
            return symbols[num]

        nums = []
        digit = 1
        while num > 0:
            rem = num % 10
            nums.append(rem * digit)
            digit *= 10
            num //= 10


        for i in range(len(nums) - 1, -1, -1):
            num = nums[i]
            if num == 0:
                continue

            digits = int(log10(num))
            value = 10 ** digits
            num = num // value

            symbol = ""
            if num * value in symbols:
                symbol = symbols[num * value]

            elif num == 4:
                symbol = symbols[5 * value]
                symbol = predecessor[symbol] + symbol

            elif num == 9:
                symbol = symbols[10 * value]
                symbol = predecessor[symbol] + symbol

            elif num < 5:
                symbol = symbols[value] * num

            else:
                symbol = symbols[5 * value]
                symbol += (predecessor[symbol] * (num - 5))

            result.append(symbol)

        return "".join(result)
