"""
Title: Letter Combinations of a Phone Number
Difficulty: Medium
Time: 30 min
URL: https://leetcode.com/problems/letter-combinations-of-a-phone-number/

Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.

A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

 

Example 1:

Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]

Example 2:

Input: digits = "2"
Output: ["a","b","c"]

 

Constraints:

1 <= digits.length <= 4

digits[i] is a digit in the range ['2', '9'].

Generated by CodeBridge
"""

class Solution:
    def letterCombinations(self, digits: str) -> List[str]:
        alphabets = ["", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wyxz"]
        results = []
        
        def dfs(index, arr):
            if len(arr) == len(digits):
                results.append("".join(arr))
                return

            digits_index = len(arr)
            number = int(digits[digits_index])
            letters = alphabets[number]

            if index >= len(letters):
                return

            dfs(index + 1, arr)
            arr.append(letters[len(letters) - index - 1])
            dfs(0, arr)

            # backtracking
            arr.pop()

        dfs(0, [])

        return results
