"""
Title: Find First and Last Position of Element in Sorted Array
Difficulty: Medium
Time: 25 min
URL: https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/

Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.

If target is not found in the array, return [-1, -1].

You must write an algorithm with O(log n) runtime complexity.

 

Example 1:

Input: nums = [5,7,7,8,8,10], target = 8
Output: [3,4]

Example 2:

Input: nums = [5,7,7,8,8,10], target = 6
Output: [-1,-1]

Example 3:

Input: nums = [], target = 0
Output: [-1,-1]

 

Constraints:

0 <= nums.length <= 105

-109 <= nums[i] <= 109

nums is a non-decreasing array.

-109 <= target <= 109

Generated by CodeBridge
"""

class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        # left = bisect.bisect_left(nums, target)
        # right = bisect.bisect_right(nums, target)
        
        # if left == len(nums) or nums[left] != target:
        #     return [-1, -1]
        
        # return [left, right-1]

        res = [-1, -1]
        n = len(nums)
        
        left = 0
        right = n - 1

        # finding the initial index
        while left <= right:
            mid = (left + right) // 2
            if nums[mid] < target:
                left = mid + 1
            elif nums[mid] > target:
                right = mid - 1
            elif mid == 0 or nums[mid] != nums[mid-1]:
                res[0] = mid
                break
            else:
                right = mid - 1

        # if the element is not found
        if res[0] == -1:
            return res

        left = 0
        right = n - 1

        # finding the last index
        while left <= right:
            mid = (left + right)//2
            if nums[mid] < target:
                left = mid + 1
            elif nums[mid] > target:
                right = mid - 1

            elif mid == n - 1 or nums[mid] != nums[mid + 1]:
                res[1] = mid
                break

            else:
                left = mid + 1

        return res