"""
Title: Sudoku Solver
Difficulty: Hard
Time: 60 min
URL: https://leetcode.com/problems/sudoku-solver/

Write a program to solve a Sudoku puzzle by filling the empty cells.

A sudoku solution must satisfy all of the following rules:

Each of the digits 1-9 must occur exactly once in each row.

Each of the digits 1-9 must occur exactly once in each column.

Each of the digits 1-9 must occur exactly once in each of the 9 3x3 sub-boxes of the grid.

The '.' character indicates empty cells.

 

Example 1:

Input: board = [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]
Output: [["5","3","4","6","7","8","9","1","2"],["6","7","2","1","9","5","3","4","8"],["1","9","8","3","4","2","5","6","7"],["8","5","9","7","6","1","4","2","3"],["4","2","6","8","5","3","7","9","1"],["7","1","3","9","2","4","8","5","6"],["9","6","1","5","3","7","2","8","4"],["2","8","7","4","1","9","6","3","5"],["3","4","5","2","8","6","1","7","9"]]
Explanation: The input board is shown above and the only valid solution is shown below:

 

Constraints:

board.length == 9

board[i].length == 9

board[i][j] is a digit or '.'.

It is guaranteed that the input board has only one solution.

Generated by CodeBridge
"""

class Solution:

    def solveSudoku(self, board: List[List[str]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """
        next = lambda row, col: [row + (col == 8), (col + 1) % 9]

        boxes = [[set() for _ in range(3)] for __ in range(3)]
        rows = [set() for _ in range(9)]
        cols = [set() for _ in range(9)]
        
        for i in range(9):
            for j in range(9):
                num = board[i][j]
                if num != ".":
                    rows[i].add(num)
                    cols[j].add(num)
                    boxes[i // 3][j // 3].add(num)
        
        def dfs(row = 0, col = 0):
            # if we covered all rows we have finished
            if row == 9:
                return True

            # if the cell is already filled we don't need to fill it
            if board[row][col] != ".":
                return dfs(*next(row, col))

            box_row = row // 3
            box_col = col // 3

            for num in range(1, 10):
                num = str(num)

                # if already found in the current row
                if num in rows[row]:
                    continue

                # if already found in the current column
                if num in cols[col]:
                    continue

                # if already found in the current box
                if num in boxes[box_row][box_col]:
                    continue

                rows[row].add(num)
                cols[col].add(num)
                boxes[box_row][box_col].add(num)
                board[row][col] = num

                if dfs(*next(row, col)):
                    return True

                board[row][col] = "."
                rows[row].discard(num)
                cols[col].discard(num)
                boxes[box_row][box_col].discard(num)

            return False

        dfs(0, 0)
