"""
Title: N-Queens
Difficulty: Hard
Time: 15 min
URL: https://leetcode.com/problems/n-queens/

The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

 

Example 1:

Input: n = 4
Output: [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]
Explanation: There exist two distinct solutions to the 4-queens puzzle as shown above

Example 2:

Input: n = 1
Output: [["Q"]]

 

Constraints:

1 <= n <= 9

Generated by CodeBridge
"""

class Solution:
    def builder(self, points):
        n = len(points)
        board = []

        for j in range(n):
            point = points[j]
            row = []
            for k in range(n):
                if j == point[0] and k == point[1]:
                    row.append("Q")
                else:
                    row.append(".")

            board.append("".join(row))

        return board
        
    def solveNQueens(self, n: int) -> List[List[str]]:
        results = []
        used_cols = [False] * n
        used_neg_diagonals = defaultdict(bool)
        used_pos_diagonals = defaultdict(bool)

        def dfs(row, path):
            if row == n:
                return results.append(self.builder(path))

            for col in range(n):
                if used_cols[col]:
                    continue

                if used_pos_diagonals[row + col]:
                    continue
                
                if used_neg_diagonals[row - col]:
                    continue

                used_cols[col] = True
                used_pos_diagonals[row + col] =True
                used_neg_diagonals[row - col] =True

                path.append([row, col])
                dfs(row + 1, path)
                path.pop()

                used_cols[col] = False
                used_pos_diagonals[row + col] = False
                used_neg_diagonals[row - col] = False
        

        dfs(0, [])

        return results
