"""
Title: N-Queens II
Difficulty: Hard
Time: 5 min
URL: https://leetcode.com/problems/n-queens-ii/

The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.

Given an integer n, return the number of distinct solutions to the n-queens puzzle.

 

Example 1:

Input: n = 4
Output: 2
Explanation: There are two distinct solutions to the 4-queens puzzle as shown.

Example 2:

Input: n = 1
Output: 1

 

Constraints:

1 <= n <= 9

Generated by CodeBridge
"""

class Solution:
    def builder(self, points):
        n = len(points)
        board = []

        for j in range(n):
            point = points[j]
            row = []
            for k in range(n):
                if j == point[0] and k == point[1]:
                    row.append("Q")
                else:
                    row.append(".")

            board.append("".join(row))

        return board
        
    def totalNQueens(self, n: int) -> List[List[str]]:
        used_cols = [False] * n
        used_neg_diagonals = defaultdict(bool)
        used_pos_diagonals = defaultdict(bool)

        self.answer = 0

        def dfs(row):
            if row == n:
                self.answer += 1
                return

            for col in range(n):
                if used_cols[col]:
                    continue

                if used_pos_diagonals[row + col]:
                    continue
                
                if used_neg_diagonals[row - col]:
                    continue

                used_cols[col] = True
                used_pos_diagonals[row + col] =True
                used_neg_diagonals[row - col] =True

                dfs(row + 1)

                used_cols[col] = False
                used_pos_diagonals[row + col] = False
                used_neg_diagonals[row - col] = False
        
        dfs(0)

        return self.answer
