"""
Title: Spiral Matrix
Difficulty: Medium
Time: 60 min
URL: https://leetcode.com/problems/spiral-matrix/

Given an m x n matrix, return all elements of the matrix in spiral order.

 

Example 1:

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,3,6,9,8,7,4,5]

Example 2:

Input: matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
Output: [1,2,3,4,8,12,11,10,9,5,6,7]

 

Constraints:

m == matrix.length

n == matrix[i].length

1 <= m, n <= 10

-100 <= matrix[i][j] <= 100

Generated by CodeBridge
"""

class Solution:

    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:
        n, m = len(matrix), len(matrix[0])
        result = []

        top, bottom = 0, n - 1
        left, right = 0, m - 1

        while top <= bottom and left <= right:
            # rightward
            for i in range(left, right + 1):
                result.append(matrix[top][i])
            top += 1

            # downward
            if left <= right:
                for i in range(top, bottom + 1):
                    result.append(matrix[i][right])
                right -= 1
            
            # leftward
            if top <= bottom:
                for i in range(right, left - 1, -1):
                    result.append(matrix[bottom][i])
                bottom -= 1

            # upward
            if left <= right:
                for i in range(bottom, top - 1, -1):
                    result.append(matrix[i][left])
                left += 1

        return result

