"""
# Insert Interval

**Difficulty:** Medium
**Tags:** Array
**URL:** https://leetcode.com/problems/insert-interval/

## Problem

You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti. You are also given an interval newInterval = [start, end] that represents the start and end of another interval.

Insert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals (merge overlapping intervals if necessary).

Return intervals after the insertion.

Note that you don&#39;t need to modify intervals in-place. You can make a new array and return it.

&nbsp;
Example 1:


Input: intervals = [[1,3],[6,9]], newInterval = [2,5]
Output: [[1,5],[6,9]]


Example 2:


Input: intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]
Output: [[1,2],[3,10],[12,16]]
Explanation: Because the new interval [4,8] overlaps with [3,5],[6,7],[8,10].


&nbsp;
Constraints:


	0 &lt;= intervals.length &lt;= 104
	intervals[i].length == 2
	0 &lt;= starti &lt;= endi &lt;= 105
	intervals is sorted by starti in ascending order.
	newInterval.length == 2
	0 &lt;= start &lt;= end &lt;= 105

---
_Generated by CodeBridge_
"""

class Solution:
    def insert(self, intervals: List[List[int]], newInterval: List[int]) -> List[List[int]]:
        newStart, newEnd = newInterval

        # check if the interval can be added at the end 
        if not intervals or newEnd < intervals[0][0]:
            return [newInterval] + intervals

        if newStart > intervals[-1][1]:
            return intervals + [newInterval]

        result = []
        inserted = False

        i = 0
        while not inserted and i < len(intervals):
            start, end = intervals[i]

            if (
                (start <= newStart <= end) or
                (start <= newEnd <= end) or
                (newStart <= start and end <= newEnd)
            ):
                inserted = True
                start = min(start, newStart)
                end = max(end, newEnd)

                while i < len(intervals) - 1 and end >= intervals[i + 1][0]:
                    end = max(end, intervals[i + 1][1])
                    i += 1

            result.append([start, end])

            if (not inserted
                and i < len(intervals) - 1 
                and newEnd < intervals[i+1][0]
            ):
                inserted = True
                result.append([newStart, newEnd])

            i += 1


        return result + intervals[i:]
