"""
Title: Spiral Matrix II
Difficulty: Medium
Time: 10 min
URL: https://leetcode.com/problems/spiral-matrix-ii/?envType=problem-list-v2&envId=matrix

Given a positive integer n, generate an n x n matrix filled with elements from 1 to n2 in spiral order.

 

Example 1:

Input: n = 3
Output: [[1,2,3],[8,9,4],[7,6,5]]

Example 2:

Input: n = 1
Output: [[1]]

 

Constraints:

1 <= n <= 20

Generated by CodeBridge
"""

class Solution:
    def generateMatrix(self, n: int) -> List[List[int]]:
        top, bottom = 0, n - 1
        left, right = 0, n - 1

        matrix = [[0] * n for _ in range(n)]
        nums = [i for i in range(1, n * n + 1)]

        j = 0
        while top <= bottom and left <= right:
            for i in range(left, right + 1):
                matrix[top][i] = nums[j]
                j += 1

            top += 1

            for i in range(top, bottom + 1):
                matrix[i][right] = nums[j]
                j += 1

            right -= 1

            for i in range(right, left - 1, -1):
                matrix[bottom][i] = nums[j]
                j += 1

            bottom -= 1

            for i in range(bottom, top - 1, -1):
                matrix[i][left] = nums[j]
                j += 1

            left += 1

        
        return matrix
