"""
Title: Rotate List
Difficulty: Medium
Time: 20 min
URL: https://leetcode.com/problems/rotate-list/description/?envType=problem-list-v2&envId=two-pointers

Given the head of a linked list, rotate the list to the right by k places.

 

Example 1:

Input: head = [1,2,3,4,5], k = 2
Output: [4,5,1,2,3]

Example 2:

Input: head = [0,1,2], k = 4
Output: [2,0,1]

 

Constraints:

The number of nodes in the list is in the range [0, 500].

-100 <= Node.val <= 100

0 <= k <= 2 * 109

Generated by CodeBridge
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def rotateRight(self, head: Optional[ListNode], k: int) -> Optional[ListNode]:
        if not head or not head.next:
            return head

        # calculate the length
        leng = 1
        fast = head
        while fast and fast.next:
            fast = fast.next
            leng += 1

        distance = k % leng

        slow = head
        for _ in range(1, leng - distance):
            slow = slow.next

        fast.next = head
        new_head = slow.next
        slow.next = None

        return new_head
