"""
Title: Minimum Path Sum
Difficulty: Medium
Time: 30 min
URL: https://leetcode.com/problems/minimum-path-sum/

Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path.

Note: You can only move either down or right at any point in time.

 

Example 1:

Input: grid = [[1,3,1],[1,5,1],[4,2,1]]
Output: 7
Explanation: Because the path 1 &rarr; 3 &rarr; 1 &rarr; 1 &rarr; 1 minimizes the sum.

Example 2:

Input: grid = [[1,2,3],[4,5,6]]
Output: 12

 

Constraints:

m == grid.length

n == grid[i].length

1 <= m, n <= 200

0 <= grid[i][j] <= 200

Generated by CodeBridge
"""

class Solution:
    def minPathSum(self, grid: List[List[int]]) -> int:
        INF = 10**9
        rows = len(grid)
        cols = len(grid[0])
        
        grid.append([INF] * cols)
        for row in grid:
            row.append(INF)

        for i in range(rows):
            for j in range(cols):
                if i == 0 and j == 0:
                    continue

                grid[i][j] = grid[i][j] + min(grid[i-1][j], grid[i][j-1])


        return grid[rows-1][cols-1]