"""
Title: Search a 2D Matrix
Difficulty: Medium
Time: 30 min
Attempts: 2
URL: https://leetcode.com/problems/search-a-2d-matrix/

You are given an m x n integer matrix matrix with the following two properties:

Each row is sorted in non-decreasing order.

The first integer of each row is greater than the last integer of the previous row.

Given an integer target, return true if target is in matrix or false otherwise.

You must write a solution in O(log(m * n)) time complexity.

 

Example 1:

Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3
Output: true

Example 2:

Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13
Output: false

 

Constraints:

m == matrix.length

n == matrix[i].length

1 <= m, n <= 100

-104 <= matrix[i][j], target <= 104

Generated by CodeBridge
"""

class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
        n = len(matrix)
        m = len(matrix[0])

        top = 0
        bottom = n - 1

        while top <= bottom:
            mid = top + (bottom - top) // 2

            if matrix[mid][0] <= target:
                top = mid + 1

            else:
                bottom = mid - 1

        if bottom == -1:
            return False
        
        row = matrix[bottom]
        index = bisect.bisect_left(row, target)

        return index < m and row[index] == target
        