"""
Title: Partition List
Difficulty: Medium
Time: 60 min
URL: https://leetcode.com/problems/partition-list/?envType=problem-list-v2&envId=two-pointers

Given the head of a linked list and a value x, partition it such that all nodes less than x come before nodes greater than or equal to x.

You should preserve the original relative order of the nodes in each of the two partitions.

 

Example 1:

Input: head = [1,4,3,2,5,2], x = 3
Output: [1,2,2,4,3,5]

Example 2:

Input: head = [2,1], x = 2
Output: [1,2]

 

Constraints:

The number of nodes in the list is in the range [0, 200].

-100 <= Node.val <= 100

-200 <= x <= 200

Generated by CodeBridge
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def length(self, head):
        itr = head
        n = 0
        while itr:
            itr = itr.next
            n += 1

        return n

    def partition(self, head: Optional[ListNode], x: int) -> Optional[ListNode]:
        if not head or not head.next:
            return head
        
        n = self.length(head)

        for j in range(n-1): # no use
            prev = None
            cur = head

            for i in range(n-j-1):
                swapped = False
                if cur.val >= x and cur.next.val < x:
                    swapped = True
                    next = cur.next
                    if not prev:
                        head = next
                    else:
                        prev.next = next

                    cur.next = next.next
                    next.next = cur

                prev = prev.next if prev else head
                if not swapped:
                    cur = cur.next


        return head
