"""
Title: Surrounded Regions
Difficulty: Medium
Time: 60 min
URL: https://leetcode.com/problems/surrounded-regions/

You are given an m x n matrix board containing letters 'X' and 'O', capture regions that are surrounded:

Connect: A cell is connected to adjacent cells horizontally or vertically.

Region: To form a region connect every 'O' cell.

Surround: A region is surrounded if none of the 'O' cells in that region are on the edge of the board. Such regions are completely enclosed by 'X' cells.

To capture a surrounded region, replace all 'O's with 'X's in-place within the original board. You do not need to return anything.

 

Example 1:

Input: board = [["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]

Output: [["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]

Explanation:

In the above diagram, the bottom region is not captured because it is on the edge of the board and cannot be surrounded.

Example 2:

Input: board = [["X"]]

Output: [["X"]]

 

Constraints:

m == board.length

n == board[i].length

1 <= m, n <= 200

board[i][j] is 'X' or 'O'.

Generated by CodeBridge
"""

class Solution:
    def solve(self, board: List[List[str]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """

        n = len(board)
        m = len(board[0])

        visited = [[False for _ in range(m)] for __ in range(n)]

        directions = [(0, 1), (0, -1), (-1, 0), (1, 0)]
        
        def in_bound(row, col):
            return -1 < row < n and -1 < col < m
        
        def dfs(row, col):
            for rd, cd in directions:
                nr, nc = row + rd, col + cd

                if not in_bound(nr, nc):
                    continue

                if board[nr][nc] == "X":
                    continue

                if visited[nr][nc]:
                    continue

                visited[nr][nc] = True

                dfs(nr, nc)


        for i in range(n):
            if not visited[i][0] and board[i][0] == "O":
                visited[i][0] = True
                dfs(i, 0)

        for i in range(n):
            if not visited[i][m - 1] and board[i][m - 1] == "O":
                visited[i][m - 1] = True
                dfs(i, m - 1)
        
        for i in range(m):
            if not visited[0][i] and board[0][i] == "O":
                visited[0][i] = True
                dfs(0, i)

        for i in range(m):
            if not visited[n - 1][i] and board[n - 1][i] == "O":
                visited[n - 1][i] = True
                dfs(n - 1, i)

        for i in range(n):
            for j in range(m):
                if not visited[i][j]:
                    board[i][j] = "X"
