"""
Title: Sort List
Difficulty: Medium
Time: 20 min
URL: https://leetcode.com/problems/sort-list/

Given the head of a linked list, return the list after sorting it in ascending order.

 

Example 1:

Input: head = [4,2,1,3]
Output: [1,2,3,4]

Example 2:

Input: head = [-1,5,3,4,0]
Output: [-1,0,3,4,5]

Example 3:

Input: head = []
Output: []

 

Constraints:

The number of nodes in the list is in the range [0, 5 * 104].

-105 <= Node.val <= 105

 

Follow up: Can you sort the linked list in O(n logn) time and O(1) memory (i.e. constant space)?

Generated by CodeBridge
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def merge(self, head1, head2):
        dummy = ListNode(0)
        itr = dummy

        itr1 = head1
        itr2 = head2

        while itr1 and itr2:
            if itr1.val <= itr2.val:
                itr.next = itr1
                itr1 = itr1.next

            else:
                itr.next = itr2
                itr2 = itr2.next

            itr = itr.next

        if itr1:
            itr.next = itr1

        if itr2:
            itr.next = itr2

        return dummy.next

    def middle(self, head):
        if not head or not head.next :
            return head

        slow = head
        fast = head.next

        while fast and fast.next:
            fast = fast.next.next
            slow = slow.next

        return slow

    def sortList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if not head or not head.next:
            return head
            
        mid = self.middle(head)
        right_start = mid.next
        mid.next = None

        left = self.sortList(head)
        right = self.sortList(right_start)

        return self.merge(left, right)