"""
Title: Number of Islands
Difficulty: Medium
Time: 25 min
URL: https://leetcode.com/problems/number-of-islands/

Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

 

Example 1:

Input: grid = [
  ["1","1","1","1","0"],
  ["1","1","0","1","0"],
  ["1","1","0","0","0"],
  ["0","0","0","0","0"]
]
Output: 1

Example 2:

Input: grid = [
  ["1","1","0","0","0"],
  ["1","1","0","0","0"],
  ["0","0","1","0","0"],
  ["0","0","0","1","1"]
]
Output: 3

 

Constraints:

m == grid.length

n == grid[i].length

1 <= m, n <= 300

grid[i][j] is '0' or '1'.

Generated by CodeBridge
"""

class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        n = len(grid)
        m = len(grid[0])
        directions = [[-1, 0], [1, 0], [0, -1], [0, 1]]

        def dfs(row, col):
            
            for row_dir, col_dir in directions:
                grid[row][col] = "0"
                new_row, new_col = row + row_dir, col + col_dir

                if new_row == -1 or new_row == n or new_col == -1 or new_col == m:
                    continue

                if grid[new_row][new_col] == "0":
                    continue

                dfs(row + row_dir, col + col_dir)

        total = 0
        for i in range(n):
            for j in range(m):
                if grid[i][j] == "1":
                    total += 1
                    dfs(i, j)

        return total