"""
# Reverse Linked List

**Difficulty:** Easy
**Tags:** Linked List, Recursion
**URL:** https://leetcode.com/problems/reverse-linked-list/

## Problem

Given the head of a singly linked list, reverse the list, and return the reversed list.

&nbsp;

Example 1:

Input: head = [1,2,3,4,5]
Output: [5,4,3,2,1]

Example 2:

Input: head = [1,2]
Output: [2,1]

Example 3:

Input: head = []
Output: []

&nbsp;

Constraints:

The number of nodes in the list is the range [0, 5000].

-5000 &lt;= Node.val &lt;= 5000

&nbsp;

Follow up: A linked list can be reversed either iteratively or recursively. Could you implement both?

---
_Generated by CodeBridge_
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if not head or not head.next:
            return head
        # after this point we start solving for linked lists with at least 2 elements 

        prev = None
        curr = head
        next = head.next

        while curr:
            curr.next = prev
            prev = curr
            curr = next
            next = next.next if next else None

        return prev

