"""
Title: Kth Largest Element in an Array
Difficulty: Medium
Time: 5 min
URL: https://leetcode.com/problems/kth-largest-element-in-an-array/

Given an integer array nums and an integer k, return the kth largest element in the array.

Note that it is the kth largest element in the sorted order, not the kth distinct element.

Can you solve it without sorting?

 

Example 1:

Input: nums = [3,2,1,5,6,4], k = 2
Output: 5

Example 2:

Input: nums = [3,2,3,1,2,4,5,5,6], k = 4
Output: 4

 

Constraints:

1 <= k <= nums.length <= 105

-104 <= nums[i] <= 104

Generated by CodeBridge
"""

class Solution:
    def findKthLargest(self, nums: List[int], k: int) -> int:
        n = len(nums)
        heap = []

        for i in range(n):
            heappush(heap, nums[i])

            if len(heap) > k:
                heappop(heap)

        return heap[0]
