"""
# Majority Element II

**Difficulty:** Medium
**Tags:** Array, Hash Table, Sorting, Counting
**URL:** https://leetcode.com/problems/majority-element-ii/

## Problem

Given an integer array of size n, find all elements that appear more than &lfloor; n/3 &rfloor; times.

&nbsp;
Example 1:


Input: nums = [3,2,3]
Output: [3]


Example 2:


Input: nums = [1]
Output: [1]


Example 3:


Input: nums = [1,2]
Output: [1,2]


&nbsp;
Constraints:


	1 &lt;= nums.length &lt;= 5 * 104
	-109 &lt;= nums[i] &lt;= 109


&nbsp;
Follow up: Could you solve the problem in linear time and in O(1) space?

---
_Generated by CodeBridge_
"""

class Solution:
    def majorityElement(self, nums: List[int]) -> List[int]:
        counts = Counter(nums)
        n = len(nums)
        return [num for num in counts if counts[num] > n // 3]