"""
Title: Sliding Window Maximum
Difficulty: Hard
Time: 10 min
URL: https://leetcode.com/problems/sliding-window-maximum/

You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window.

 

Example 1:

Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]
Explanation: 
Window position                Max
---------------               -----
[1  3  -1] -3  5  3  6  7       3
 1 [3  -1  -3] 5  3  6  7       3
 1  3 [-1  -3  5] 3  6  7       5
 1  3  -1 [-3  5  3] 6  7       5
 1  3  -1  -3 [5  3  6] 7       6
 1  3  -1  -3  5 [3  6  7]      7

Example 2:

Input: nums = [1], k = 1
Output: [1]

 

Constraints:

1 <= nums.length <= 105

-104 <= nums[i] <= 104

1 <= k <= nums.length

Generated by CodeBridge
"""

class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        n = len(nums)
        result = [0] * (n - k + 1)

        max_queue = deque()
        
        for i in range(k):
            while max_queue and max_queue[-1] < nums[i]:
                max_queue.pop()
            
            max_queue.append(nums[i])

        left = 0
        for right in range(k, n):
            result[left] = max_queue[0]

            if max_queue and nums[left] == max_queue[0]:
                max_queue.popleft()

            left += 1

            while max_queue and max_queue[-1] < nums[right]:
                max_queue.pop()

            max_queue.append(nums[right])

        result[-1] = max_queue[0]

        return result

