"""
Title: Word Pattern
Difficulty: Easy
Time: 10 min
URL: https://leetcode.com/problems/word-pattern/

Given a pattern and a string s, find if s follows the same pattern.

Here follow means a full match, such that there is a bijection between a letter in pattern and a non-empty word in s. Specifically:

Each letter in pattern maps to exactly one unique word in s.

Each unique word in s maps to exactly one letter in pattern.

No two letters map to the same word, and no two words map to the same letter.

 

Example 1:

Input: pattern = "abba", s = "dog cat cat dog"

Output: true

Explanation:

The bijection can be established as:

'a' maps to "dog".

'b' maps to "cat".

Example 2:

Input: pattern = "abba", s = "dog cat cat fish"

Output: false

Example 3:

Input: pattern = "aaaa", s = "dog cat cat dog"

Output: false

 

Constraints:

1 <= pattern.length <= 300

pattern contains only lower-case English letters.

1 <= s.length <= 3000

s contains only lowercase English letters and spaces ' '.

s does not contain any leading or trailing spaces.

All the words in s are separated by a single space.

Generated by CodeBridge
"""

class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
        n = len(pattern)
        s = s.split()

        if len(s) != n:
            return False

        # maps characters with the words
        char_to_word = {}
        # maps words with the characters
        word_to_char = {}

        # build the mapp, while checking invalidity
        for i in range(n):
            char = pattern[i]
            word = s[i]

            # if the character has been mapped to another word before (invalid pattern)
            if char in char_to_word and char_to_word[char] != word:
                return False

            # if the word has been mapped to another character before (invalid pattern)
            if word in word_to_char and word_to_char[word] != char:
                return False

            char_to_word[char] = word
            word_to_char[word] = char

        # if nothing has been invalid then, it is true
        return True