"""
# Bulls and Cows

**Difficulty:** Medium
**Tags:** Hash Table, String, Counting
**URL:** https://leetcode.com/problems/bulls-and-cows/

## Problem

You are playing the Bulls and Cows game with your friend.

You write down a secret number and ask your friend to guess what the number is. When your friend makes a guess, you provide a hint with the following info:


	The number of &quot;bulls&quot;, which are digits in the guess that are in the correct position.
	The number of &quot;cows&quot;, which are digits in the guess that are in your secret number but are located in the wrong position. Specifically, the non-bull digits in the guess that could be rearranged such that they become bulls.


Given the secret number secret and your friend&#39;s guess guess, return the hint for your friend&#39;s guess.

The hint should be formatted as &quot;xAyB&quot;, where x is the number of bulls and y is the number of cows. Note that both secret and guess may contain duplicate digits.

&nbsp;
Example 1:


Input: secret = &quot;1807&quot;, guess = &quot;7810&quot;
Output: &quot;1A3B&quot;
Explanation: Bulls are connected with a &#39;|&#39; and cows are underlined:
&quot;1807&quot;
  |
&quot;7810&quot;

Example 2:


Input: secret = &quot;1123&quot;, guess = &quot;0111&quot;
Output: &quot;1A1B&quot;
Explanation: Bulls are connected with a &#39;|&#39; and cows are underlined:
&quot;1123&quot;        &quot;1123&quot;
  |      or     |
&quot;0111&quot;        &quot;0111&quot;
Note that only one of the two unmatched 1s is counted as a cow since the non-bull digits can only be rearranged to allow one 1 to be a bull.


&nbsp;
Constraints:


	1 &lt;= secret.length, guess.length &lt;= 1000
	secret.length == guess.length
	secret and guess consist of digits only.

---
_Generated by CodeBridge_
"""

class Solution:
    def getHint(self, secret: str, guess: str) -> str:
        secret_dict = Counter(secret)
        seen = set()
        bulls = 0
        cows = 0

        # count the bulls
        for i in range(len(guess)):
            char = guess[i]
            if guess[i] in secret_dict and secret[i] == char:
                bulls += 1
                seen.add(i)
                secret_dict[char] -= 1

                if secret_dict[char] == 0:
                    del secret_dict[char]

        # count the cows
        for i in range(len(guess)):
            char = guess[i]
            if i not in seen and char in secret_dict:
                cows += 1
                secret_dict[char] -= 1

                if secret_dict[char] == 0:
                    del secret_dict[char]            

        

        return f"{bulls}A{cows}B"