"""
Title: Remove Invalid Parentheses
Difficulty: Hard
Time: 30 min
URL: https://leetcode.com/problems/remove-invalid-parentheses/

Given a string s that contains parentheses and letters, remove the minimum number of invalid parentheses to make the input string valid.

Return a list of unique strings that are valid with the minimum number of removals. You may return the answer in any order.

 

Example 1:

Input: s = "()())()"
Output: ["(())()","()()()"]

Example 2:

Input: s = "(a)())()"
Output: ["(a())()","(a)()()"]

Example 3:

Input: s = ")("
Output: [""]

 

Constraints:

1 <= s.length <= 25

s consists of lowercase English letters and parentheses '(' and ')'.

There will be at most 20 parentheses in s.

Generated by CodeBridge
"""

class Solution:
    def is_valid(self, string):
        count = 0
        for c in string:
            if c == "(":
                count += 1
            elif c == ")":
                count -= 1
                if count < 0:
                    return False
        return count == 0

    def removeInvalidParentheses(self, s: str) -> List[str]:
        queue = deque([s])
        visited = set([s])
        results = []
        found = False

        while not found and queue:
            level_size = len(queue)

            for _ in range(level_size):
                curr = queue.popleft()

                if self.is_valid(curr):
                    results.append(curr)
                    found = True

                if found:
                    continue  # don't generate next level

                for i in range(len(curr)):
                    if curr[i] not in "()":
                        continue

                    new_str = curr[:i] + curr[i+1:]

                    if new_str not in visited:
                        visited.add(new_str)
                        queue.append(new_str)
                        

        return results