"""
Title: Additive Number
Difficulty: Medium
Time: 20 min
Attempts: 1
URL: https://leetcode.com/problems/additive-number/submissions/1978659651/?envType=problem-list-v2&envId=backtracking

An additive number is a string whose digits can form an additive sequence.

A valid additive sequence should contain at least three numbers. Except for the first two numbers, each subsequent number in the sequence must be the sum of the preceding two.

Given a string containing only digits, return true if it is an additive number or false otherwise.

Note: Numbers in the additive sequence cannot have leading zeros, so sequence 1, 2, 03 or 1, 02, 3 is invalid.

 

Example 1:

Input: "112358"
Output: true
Explanation: 
The digits can form an additive sequence: 1, 1, 2, 3, 5, 8. 
1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8

Example 2:

Input: "199100199"
Output: true
Explanation: 
The additive sequence is: 1, 99, 100, 199. 
1 + 99 = 100, 99 + 100 = 199

 

Constraints:

1 <= num.length <= 35

num consists only of digits.

 

Follow up: How would you handle overflow for very large input integers?

Generated by CodeBridge
"""

class Solution:
    def isAdditiveNumber(self, s: str) -> bool:
        n = len(s)

        def dfs(index, father = None, gfather = None, ggfather = None):
            if index == n:
                return ggfather is not None

            num = []

            for i in range(index, n):
                num.append(s[i])

                # pruning

                if len(num) > 1 and num[0] == "0":
                    return False

                number = int("".join(num))

                if father is not None and gfather is not None and number != father + gfather:
                    continue
                
                # end

                if dfs(i + 1, number, father,gfather):
                    return True

            return False

        return dfs(0)