"""
Title: Count of Smaller Numbers After Self
Difficulty: Hard
Time: 20 min
URL: https://leetcode.com/problems/count-of-smaller-numbers-after-self/

Given an integer array nums, return an integer array counts where counts[i] is the number of smaller elements to the right of nums[i].

 

Example 1:

Input: nums = [5,2,6,1]
Output: [2,1,1,0]
Explanation:
To the right of 5 there are 2 smaller elements (2 and 1).
To the right of 2 there is only 1 smaller element (1).
To the right of 6 there is 1 smaller element (1).
To the right of 1 there is 0 smaller element.

Example 2:

Input: nums = [-1]
Output: [0]

Example 3:

Input: nums = [-1,-1]
Output: [0,0]

 

Constraints:

1 <= nums.length <= 105

-104 <= nums[i] <= 104

Generated by CodeBridge
"""

class Solution:
    def __init__(self):
        self.mapp = Counter()

    def bisectLeft(self, arr, target):
        left = 0
        right = len(arr) - 1

        while left <= right:
            mid = left + (right - left) // 2

            if arr[mid][0] >= target:
                right = mid - 1
            else:
                left = mid + 1

        return left

    def merge(self, left, right):
        i = 0
        j = 0

        result = []
        
        while i < len(left) and j < len(right):
            if right[j][0] >= left[i][0]:
                result.append(right[j])
                j += 1

            else:
                self.mapp[left[i][1]] += (len(right) - j)
                result.append(left[i])
                i += 1

        result.extend(left[i:])
        result.extend(right[j:])

        return result

    def mergeSort(self, left, right, arr):
        if left == right:
            return [arr[left]]

        mid = left + (right - left) // 2
        left_half = self.mergeSort(left, mid, arr)
        right_half = self.mergeSort(mid + 1, right, arr)

        return self.merge(left_half, right_half)

    def countSmaller(self, nums: List[int]) -> List[int]:
        n = len(nums)
        indexed_nums = [(num, i) for i, num in enumerate(nums)]
        self.mergeSort(0, n - 1, indexed_nums)

        return [self.mapp[i] for i in range(n)]
