"""
Title: Intersection of Two Arrays
Difficulty: Easy
Time: 2 min
URL: https://leetcode.com/problems/intersection-of-two-arrays/?envType=problem-list-v2&envId=hash-table

Given two integer arrays nums1 and nums2, return an array of their intersection. Each element in the result must be unique and you may return the result in any order.

 

Example 1:

Input: nums1 = [1,2,2,1], nums2 = [2,2]
Output: [2]

Example 2:

Input: nums1 = [4,9,5], nums2 = [9,4,9,8,4]
Output: [9,4]
Explanation: [4,9] is also accepted.

 

Constraints:

1 <= nums1.length, nums2.length <= 1000

0 <= nums1[i], nums2[i] <= 1000

Generated by CodeBridge
"""

class Solution {
    public int[] intersection(int[] nums1, int[] nums2) {
        // Sort both arrays
        Arrays.sort(nums1);
        Arrays.sort(nums2);

        // Initialize two pointers
        int N = nums1.length;
        int M = nums2.length;
        int p1 = 0;
        int p2 = 0;
        
        // Create set that stores integers appearing in both arrays
        Set<Integer> intersection = new HashSet<>();

        // Iterate the pointers from left to right
        while (p1 < N && p2 < M) {
            // Add a value to the set if values at both pointers equal
            if (nums1[p1] == nums2[p2]) {
                intersection.add(nums1[p1]);
                p1++;
                p2++;
            }
            // Otherwise, increment the pointer of the smaller integer
            else if (nums1[p1] < nums2[p2]) {
                p1++;
            }
            else {
                p2++;
            }
        }

        // Convert intersection to an array
        int K = intersection.size();
        int[] result = new int[K];
        int curr = 0;
        for (int x: intersection) {
            result[curr++] = x;
        }

        //Return the result
        return result;
    }
}