"""
Title: Ransom Note
Difficulty: Easy
Time: 5 min
URL: https://leetcode.com/problems/ransom-note/

Given two strings ransomNote and magazine, return true if ransomNote can be constructed by using the letters from magazine and false otherwise.

Each letter in magazine can only be used once in ransomNote.

 

Example 1:

Input: ransomNote = "a", magazine = "b"
Output: false

Example 2:

Input: ransomNote = "aa", magazine = "ab"
Output: false

Example 3:

Input: ransomNote = "aa", magazine = "aab"
Output: true

 

Constraints:

1 <= ransomNote.length, magazine.length <= 105

ransomNote and magazine consist of lowercase English letters.

Generated by CodeBridge
"""

class Solution:
    def canConstruct(self, ransomNote: str, magazine: str) -> bool:
        magazine_counts = Counter(magazine)

        for char in ransomNote:
            if char not in magazine_counts:
                return False

            magazine_counts[char] -= 1

            if magazine_counts[char] == 0:
                del magazine_counts[char]

        return True