"""
Title: Elimination Game
Difficulty: Medium
Time: 25 min
URL: https://leetcode.com/problems/elimination-game/

You have a list arr of all integers in the range [1, n] sorted in a strictly increasing order. Apply the following algorithm on arr:

Starting from left to right, remove the first number and every other number afterward until you reach the end of the list.

Repeat the previous step again, but this time from right to left, remove the rightmost number and every other number from the remaining numbers.

Keep repeating the steps again, alternating left to right and right to left, until a single number remains.

Given the integer n, return the last number that remains in arr.

 

Example 1:

Input: n = 9
Output: 6
Explanation:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = [2, 4, 6, 8]
arr = [2, 6]
arr = [6]

Example 2:

Input: n = 1
Output: 1

 

Constraints:

1 <= n <= 109

Generated by CodeBridge
"""

class Solution:
    def lastRemaining(self, n: int) -> int:

        def rec(left, right, dir = 0, gap = 1):
            if left >= right:
                return left

            length = (right - left) // gap + 1

            if dir == 0:
                left += gap
                right -= gap * (length % 2)

            if dir == 1:
                right -= gap
                left += gap * (length % 2)

            gap *= 2
            dir = 1 - dir

            return rec(left, right, dir, gap)

        return rec(1, n - (n % 2))


