"""
Title: Longest Repeating Character Replacement
Difficulty: Medium
Time: 10 min
URL: https://leetcode.com/problems/longest-repeating-character-replacement/

You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times.

Return the length of the longest substring containing the same letter you can get after performing the above operations.

 

Example 1:

Input: s = "ABAB", k = 2
Output: 4
Explanation: Replace the two 'A's with two 'B's or vice versa.

Example 2:

Input: s = "AABABBA", k = 1
Output: 4
Explanation: Replace the one 'A' in the middle with 'B' and form "AABBBBA".
The substring "BBBB" has the longest repeating letters, which is 4.
There may exists other ways to achieve this answer too.

 

Constraints:

1 <= s.length <= 105

s consists of only uppercase English letters.

0 <= k <= s.length

Generated by CodeBridge
"""

class Solution:
    def characterReplacement(self, s: str, k: int) -> int:
        def isInValid(counts, k):
            max_count = 0
            total = 0

            for char in counts:
                total += counts[char]
                max_count = max(max_count, counts[char])

            return total - max_count > k
            
        n = len(s)
        longest = 0
        counts = Counter()

        left = 0
        for right in range(n):
            counts[s[right]] += 1

            while isInValid(counts, k):
                counts[s[left]] -= 1
                left += 1

            longest = max(longest, right - left + 1)

        return longest