"""
Title: Path Sum III
Difficulty: Medium
Time: 60 min
URL: https://leetcode.com/problems/path-sum-iii/

Given the root of a binary tree and an integer targetSum, return the number of paths where the sum of the values along the path equals targetSum.

The path does not need to start or end at the root or a leaf, but it must go downwards (i.e., traveling only from parent nodes to child nodes).

 

Example 1:

Input: root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8
Output: 3
Explanation: The paths that sum to 8 are shown.

Example 2:

Input: root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22
Output: 3

 

Constraints:

The number of nodes in the tree is in the range [0, 1000].

-109 <= Node.val <= 109

-1000 <= targetSum <= 1000

Generated by CodeBridge
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def pathSum(self, root: Optional[TreeNode], targetSum: int) -> int:
        sums = Counter()
        sums[0] = 1

        def dfs(node, target, acc):
            if not node:
                return 0
            
            acc += node.val

            need = acc - target

            count = sums[need]

            sums[acc] += 1

            count += dfs(node.left, target, acc)
            count += dfs(node.right, target, acc)

            # Backtracking
            sums[acc] -= 1

            return count

        return dfs(root, targetSum, 0)
