"""
Title: Find All Anagrams in a String
Difficulty: Medium
Time: 10 min
URL: https://leetcode.com/problems/find-all-anagrams-in-a-string/

Given two strings s and p, return an array of all the start indices of p's anagrams in s. You may return the answer in any order.

 

Example 1:

Input: s = "cbaebabacd", p = "abc"
Output: [0,6]
Explanation:
The substring with start index = 0 is "cba", which is an anagram of "abc".
The substring with start index = 6 is "bac", which is an anagram of "abc".

Example 2:

Input: s = "abab", p = "ab"
Output: [0,1,2]
Explanation:
The substring with start index = 0 is "ab", which is an anagram of "ab".
The substring with start index = 1 is "ba", which is an anagram of "ab".
The substring with start index = 2 is "ab", which is an anagram of "ab".

 

Constraints:

1 <= s.length, p.length <= 3 * 104

s and p consist of lowercase English letters.

Generated by CodeBridge
"""

class Solution:
    def findAnagrams(self, s: str, p: str) -> List[int]:
        n = len(s)
        k = len(p)
        result = []

        countS = Counter(s[:k])
        countP = Counter(p)

        if countS == countP:
            result.append(0)

        left = 0
        for right in range(k, n):
            countS[s[right]] += 1

            left_char = s[left]
            countS[left_char] -= 1

            if countS[left_char] == 0:
                del countS[left_char]

            left += 1

            if countS == countP:
                result.append(left)

        return result

