"""
# Find All Duplicates in an Array

**Difficulty:** Medium
**Tags:** Array, Hash Table, Sorting
**URL:** https://leetcode.com/problems/find-all-duplicates-in-an-array/

## Problem

Given an integer array nums of length n where all the integers of nums are in the range [1, n] and each integer appears at most twice, return an array of all the integers that appears twice.

You must write an algorithm that runs in O(n) time and uses only constant auxiliary space, excluding the space needed to store the output

&nbsp;
Example 1:
Input: nums = [4,3,2,7,8,2,3,1]
Output: [2,3]
Example 2:
Input: nums = [1,1,2]
Output: [1]
Example 3:
Input: nums = [1]
Output: []

&nbsp;
Constraints:


	n == nums.length
	1 &lt;= n &lt;= 105
	1 &lt;= nums[i] &lt;= n
	Each element in nums appears once or twice.

---
_Generated by CodeBridge_
"""

class Solution:
    def findDuplicates(self, nums: List[int]) -> List[int]:
        result = []

        for i in range(len(nums)):
            index = abs(nums[i]) - 1

            if nums[index] < 0:
                result.append(index + 1)
                
            else:
                nums[index] = - nums[index]

        return result