"""
Title: Non-decreasing Subsequences
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/non-decreasing-subsequences/?envType=problem-list-v2&envId=backtracking

Given an integer array nums, return all the different possible non-decreasing subsequences of the given array with at least two elements. You may return the answer in any order.

 

Example 1:

Input: nums = [4,6,7,7]
Output: [[4,6],[4,6,7],[4,6,7,7],[4,7],[4,7,7],[6,7],[6,7,7],[7,7]]

Example 2:

Input: nums = [4,4,3,2,1]
Output: [[4,4]]

 

Constraints:

1 <= nums.length <= 15

-100 <= nums[i] <= 100

Generated by CodeBridge
"""

class Solution:
    def findSubsequences(self, nums: List[int]) -> List[List[int]]:
        results = []
        n = len(nums)

        arr = []

        def dfs(index):
            
            if len(arr) >= 2:
                results.append(arr[:])

            used = set()
            
            for i in range(index, n):
                if nums[i] in used:
                    continue

                if arr and nums[i] < arr[-1]:
                    continue

                used.add(nums[i])

                arr.append(nums[i])
                dfs(i + 1)
                arr.pop()

        dfs(0)

        return results