"""
Title: Diagonal Traverse
Difficulty: Medium
Time: 30 min
URL: https://leetcode.com/problems/diagonal-traverse/

Given an m x n matrix mat, return an array of all the elements of the array in a diagonal order.

 

Example 1:

Input: mat = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,4,7,5,3,6,8,9]

Example 2:

Input: mat = [[1,2],[3,4]]
Output: [1,2,3,4]

 

Constraints:

m == mat.length

n == mat[i].length

1 <= m, n <= 104

1 <= m * n <= 104

-105 <= mat[i][j] <= 105

Generated by CodeBridge
"""

class Solution:
    def findDiagonalOrder(self, mat: List[List[int]]) -> List[int]:
        result = []

        # build the map (key = sum of the indices) and (value = array of the indices that give that sum)
        mapp = defaultdict(list)
        for i in range(len(mat)):
            for j in range(len(mat[0])):
                mapp[i + j].append((i, j))

        for m, indices in mapp.items():
            # for odd sums
            if m % 2 != 0:
                for i, j in indices:
                    result.append(mat[i][j])

            else:
                for i, j in reversed(indices):
                    result.append(mat[i][j])

        return result