"""
Title: Contiguous Array
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/contiguous-array/

Given a binary array nums, return the maximum length of a contiguous subarray with an equal number of 0 and 1.

 

Example 1:

Input: nums = [0,1]
Output: 2
Explanation: [0, 1] is the longest contiguous subarray with an equal number of 0 and 1.

Example 2:

Input: nums = [0,1,0]
Output: 2
Explanation: [0, 1] (or [1, 0]) is a longest contiguous subarray with equal number of 0 and 1.

Example 3:

Input: nums = [0,1,1,1,1,1,0,0,0]
Output: 6
Explanation: [1,1,1,0,0,0] is the longest contiguous subarray with equal number of 0 and 1.

 

Constraints:

1 <= nums.length <= 105

nums[i] is either 0 or 1.

Generated by CodeBridge
"""

class Solution:
    def findMaxLength(self, nums: List[int]) -> int:
        for i, num in enumerate(nums):
            nums[i] = (2*num - 1)
        
        k = 0
        seen = Counter()
        seen[0] = -1
        longest = 0
        
        prefix = 0
        for i, num in enumerate(nums):
            prefix += num
            need = prefix - k

            if need in seen:
                longest = max(longest, i - seen[need])

            if prefix not in seen:
                seen[prefix] = i

        return longest