"""
# Find Duplicate File in System

**Difficulty:** Medium
**Tags:** Array, Hash Table, String
**URL:** https://leetcode.com/problems/find-duplicate-file-in-system/

## Problem

Given a list paths of directory info, including the directory path, and all the files with contents in this directory, return all the duplicate files in the file system in terms of their paths. You may return the answer in any order.

A group of duplicate files consists of at least two files that have the same content.

A single directory info string in the input list has the following format:


	&quot;root/d1/d2/.../dm f1.txt(f1_content) f2.txt(f2_content) ... fn.txt(fn_content)&quot;


It means there are n files (f1.txt, f2.txt ... fn.txt) with content (f1_content, f2_content ... fn_content) respectively in the directory &quot;root/d1/d2/.../dm&quot;. Note that n &gt;= 1 and m &gt;= 0. If m = 0, it means the directory is just the root directory.

The output is a list of groups of duplicate file paths. For each group, it contains all the file paths of the files that have the same content. A file path is a string that has the following format:


	&quot;directory_path/file_name.txt&quot;


&nbsp;
Example 1:
Input: paths = ["root/a 1.txt(abcd) 2.txt(efgh)","root/c 3.txt(abcd)","root/c/d 4.txt(efgh)","root 4.txt(efgh)"]
Output: [["root/a/2.txt","root/c/d/4.txt","root/4.txt"],["root/a/1.txt","root/c/3.txt"]]
Example 2:
Input: paths = ["root/a 1.txt(abcd) 2.txt(efgh)","root/c 3.txt(abcd)","root/c/d 4.txt(efgh)"]
Output: [["root/a/2.txt","root/c/d/4.txt"],["root/a/1.txt","root/c/3.txt"]]

&nbsp;
Constraints:


	1 &lt;= paths.length &lt;= 2 * 104
	1 &lt;= paths[i].length &lt;= 3000
	1 &lt;= sum(paths[i].length) &lt;= 5 * 105
	paths[i] consist of English letters, digits, &#39;/&#39;, &#39;.&#39;, &#39;(&#39;, &#39;)&#39;, and &#39; &#39;.
	You may assume no files or directories share the same name in the same directory.
	You may assume each given directory info represents a unique directory. A single blank space separates the directory path and file info.


&nbsp;
Follow up:


	Imagine you are given a real file system, how will you search files? DFS or BFS?
	If the file content is very large (GB level), how will you modify your solution?
	If you can only read the file by 1kb each time, how will you modify your solution?
	What is the time complexity of your modified solution? What is the most time-consuming part and memory-consuming part of it? How to optimize?
	How to make sure the duplicated files you find are not false positive?

---
_Generated by CodeBridge_
"""

public class Solution {
    public List < List < String >> findDuplicate(String[] paths) {
        List < String[] > list = new ArrayList < > ();
        for (String path: paths) {
            String[] values = path.split(" ");
            for (int i = 1; i < values.length; i++) {
                String[] name_cont = values[i].split("\\(");
                name_cont[1] = name_cont[1].replace(")", "");
                list.add(new String[] {
                    values[0] + "/" + name_cont[0], name_cont[1]
                });
            }
        }
        boolean[] visited = new boolean[list.size()];
        List < List < String >> res = new ArrayList < > ();
        for (int i = 0; i < list.size() - 1; i++) {
            if (visited[i])
                continue;
            List < String > l = new ArrayList < > ();
            for (int j = i + 1; j < list.size(); j++) {
                if (list.get(i)[1].equals(list.get(j)[1])) {
                    l.add(list.get(j)[0]);
                    visited[j] = true;
                }
            }
            if (l.size() > 0) {
                l.add(list.get(i)[0]);
                res.add(l);
            }
        }
        return res;
    }
}
