"""
Title: Partition Labels
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/partition-labels/

You are given a string s. We want to partition the string into as many parts as possible so that each letter appears in at most one part. For example, the string "ababcc" can be partitioned into ["abab", "cc"], but partitions such as ["aba", "bcc"] or ["ab", "ab", "cc"] are invalid.

Note that the partition is done so that after concatenating all the parts in order, the resultant string should be s.

Return a list of integers representing the size of these parts.

 

Example 1:

Input: s = "ababcbacadefegdehijhklij"
Output: [9,7,8]
Explanation:
The partition is "ababcbaca", "defegde", "hijhklij".
This is a partition so that each letter appears in at most one part.
A partition like "ababcbacadefegde", "hijhklij" is incorrect, because it splits s into less parts.

Example 2:

Input: s = "eccbbbbdec"
Output: [10]

 

Constraints:

1 <= s.length <= 500

s consists of lowercase English letters.

Generated by CodeBridge
"""

class Solution:
    def partitionLabels(self, s: str) -> List[int]:
        n = len(s)
        mapp = {s[i] : i for i in range(n)}
        result = []

        start = 0
        left = 0
        while start < n:
            right = mapp[s[left]]

            while left < n and left <= right:
                right = max(right, mapp[s[left]])
                left += 1

            result.append(right - start + 1)
            start = left

        return result

