"""
# Subdomain Visit Count

**Difficulty:** Medium
**Tags:** Array, Hash Table, String, Counting
**URL:** https://leetcode.com/problems/subdomain-visit-count/

## Problem

A website domain &quot;discuss.leetcode.com&quot; consists of various subdomains. At the top level, we have &quot;com&quot;, at the next level, we have &quot;leetcode.com&quot;&nbsp;and at the lowest level, &quot;discuss.leetcode.com&quot;. When we visit a domain like &quot;discuss.leetcode.com&quot;, we will also visit the parent domains &quot;leetcode.com&quot; and &quot;com&quot; implicitly.

A count-paired domain is a domain that has one of the two formats &quot;rep d1.d2.d3&quot; or &quot;rep d1.d2&quot; where rep is the number of visits to the domain and d1.d2.d3 is the domain itself.


	For example, &quot;9001 discuss.leetcode.com&quot; is a count-paired domain that indicates that discuss.leetcode.com was visited 9001 times.


Given an array of count-paired domains cpdomains, return an array of the count-paired domains of each subdomain in the input. You may return the answer in any order.

&nbsp;
Example 1:


Input: cpdomains = [&quot;9001 discuss.leetcode.com&quot;]
Output: [&quot;9001 leetcode.com&quot;,&quot;9001 discuss.leetcode.com&quot;,&quot;9001 com&quot;]
Explanation: We only have one website domain: &quot;discuss.leetcode.com&quot;.
As discussed above, the subdomain &quot;leetcode.com&quot; and &quot;com&quot; will also be visited. So they will all be visited 9001 times.


Example 2:


Input: cpdomains = [&quot;900 google.mail.com&quot;, &quot;50 yahoo.com&quot;, &quot;1 intel.mail.com&quot;, &quot;5 wiki.org&quot;]
Output: [&quot;901 mail.com&quot;,&quot;50 yahoo.com&quot;,&quot;900 google.mail.com&quot;,&quot;5 wiki.org&quot;,&quot;5 org&quot;,&quot;1 intel.mail.com&quot;,&quot;951 com&quot;]
Explanation: We will visit &quot;google.mail.com&quot; 900 times, &quot;yahoo.com&quot; 50 times, &quot;intel.mail.com&quot; once and &quot;wiki.org&quot; 5 times.
For the subdomains, we will visit &quot;mail.com&quot; 900 + 1 = 901 times, &quot;com&quot; 900 + 50 + 1 = 951 times, and &quot;org&quot; 5 times.


&nbsp;
Constraints:


	1 &lt;= cpdomain.length &lt;= 100
	1 &lt;= cpdomain[i].length &lt;= 100
	cpdomain[i] follows either the &quot;repi d1i.d2i.d3i&quot; format or the &quot;repi d1i.d2i&quot; format.
	repi is an integer in the range [1, 104].
	d1i, d2i, and d3i consist of lowercase English letters.

---
_Generated by CodeBridge_
"""

class Solution:
    def subdomainVisits(self, cpdomains: List[str]) -> List[str]:
        counts = defaultdict(int)
        
        for cpdomain in cpdomains:
            count, domain = cpdomain.split()
            domains = domain.split(".")
            
            subdomain = ""
            for i in range(len(domains) - 1, -1, -1):
                subdomain = f"{domains[i]}.{subdomain}" if subdomain else domains[i]
                counts[subdomain] += int(count)


        return [f"{count} {subdomain}" for subdomain, count in counts.items()]