"""
Title: Score of Parentheses
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/score-of-parentheses/?envType=problem-list-v2&envId=stack

Given a balanced parentheses string s, return the score of the string.

The score of a balanced parentheses string is based on the following rule:

"()" has score 1.

AB has score A + B, where A and B are balanced parentheses strings.

(A) has score 2 * A, where A is a balanced parentheses string.

 

Example 1:

Input: s = "()"
Output: 1

Example 2:

Input: s = "(())"
Output: 2

Example 3:

Input: s = "()()"
Output: 2

 

Constraints:

2 <= s.length <= 50

s consists of only '(' and ')'.

s is a balanced parentheses string.

Generated by CodeBridge
"""

class Solution:
    def scoreOfParentheses(self, s: str) -> int:
        stack = []
        score = 0

        depth = 0
        for char in s:
            if char == "(":
                stack.append(char)
                depth = len(stack)
            else:
                score += int(2 ** (depth - 1))
                depth = 0
                stack.pop()

        return score