"""
Title: Transpose Matrix
Difficulty: Easy
Time: 5 min
URL: https://leetcode.com/problems/transpose-matrix/description/?utm_source=chatgpt.com

Given a 2D integer array matrix, return the transpose of matrix.

The transpose of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.

 

Example 1:

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[1,4,7],[2,5,8],[3,6,9]]

Example 2:

Input: matrix = [[1,2,3],[4,5,6]]
Output: [[1,4],[2,5],[3,6]]

 

Constraints:

m == matrix.length

n == matrix[i].length

1 <= m, n <= 1000

1 <= m * n <= 105

-109 <= matrix[i][j] <= 109

Generated by CodeBridge
"""

class Solution:
    def transpose(self, matrix: List[List[int]]) -> List[List[int]]:
        # rows = len(matrix)
        # cols = len(matrix[0])

        # we create a matix tha can hold the transpose of the current matrix
        result = [[0] * rows for _ in range(cols)]

        # we iterater over the elements of the current matrix,
        # and put them on the other matrix in their transposed position
        for i in range(rows):
            for j in range(cols):
                result[j][i] = matrix[i][j]

        return result


        # this does all the above in one line
        return [list(row) for row in zip(*matrix)]
