"""
Title: Spiral Matrix III
Difficulty: Medium
Time: 60 min
Attempts: 0
URL: https://leetcode.com/problems/spiral-matrix-iii/submissions/1921154440/

You start at the cell (rStart, cStart) of an rows x cols grid facing east. The northwest corner is at the first row and column in the grid, and the southeast corner is at the last row and column.

You will walk in a clockwise spiral shape to visit every position in this grid. Whenever you move outside the grid's boundary, we continue our walk outside the grid (but may return to the grid boundary later.). Eventually, we reach all rows * cols spaces of the grid.

Return an array of coordinates representing the positions of the grid in the order you visited them.

 

Example 1:

Input: rows = 1, cols = 4, rStart = 0, cStart = 0
Output: [[0,0],[0,1],[0,2],[0,3]]

Example 2:

Input: rows = 5, cols = 6, rStart = 1, cStart = 4
Output: [[1,4],[1,5],[2,5],[2,4],[2,3],[1,3],[0,3],[0,4],[0,5],[3,5],[3,4],[3,3],[3,2],[2,2],[1,2],[0,2],[4,5],[4,4],[4,3],[4,2],[4,1],[3,1],[2,1],[1,1],[0,1],[4,0],[3,0],[2,0],[1,0],[0,0]]

 

Constraints:

1 <= rows, cols <= 100

0 <= rStart < rows

0 <= cStart < cols

Generated by CodeBridge
"""

class Solution:
    
    def spiralMatrixIII(self, rows: int, cols: int, rStart: int, cStart: int) -> List[List[int]]:
        n, m = rows, cols
        top = rStart
        left = cStart
        bottom = top + 1
        right = left + 1

        result = [[rStart, cStart]]

        while top >= 0 or bottom <= n - 1 or left >= 0 or right <= m - 1:
            # rightward
            if top >= 0:
                start = max(left + 1, 0)
                end = min(right + 1, m)

                for i in range(start, end):
                    result.append([top, i])

            left -= 1
                
            # downward
            if right <= m-1:
                start = max(top + 1, 0)
                end = min(bottom + 1, n)

                for i in range(start,  end):
                    result.append([i, right])

            top -= 1

            # leftward
            if bottom <= n-1:
                start = min(right - 1, m - 1)
                end = max(left - 1, -1)

                for i in range(start, end, -1):
                    result.append([bottom, i])

            right += 1

            # upward
            if left >= 0:
                start = min(bottom - 1, n - 1)
                end = max(top - 1, -1)

                for i in range(start, end, -1):
                    result.append([i, left])

            bottom += 1


        return result

