"""
Title: Binary Subarrays With Sum
Difficulty: Medium
Time: 5 min
URL: https://leetcode.com/problems/binary-subarrays-with-sum/

Given a binary array nums and an integer goal, return the number of non-empty subarrays with a sum goal.

A subarray is a contiguous part of the array.

 

Example 1:

Input: nums = [1,0,1,0,1], goal = 2
Output: 4
Explanation: The 4 subarrays are bolded and underlined below:
[1,0,1,0,1]
[1,0,1,0,1]
[1,0,1,0,1]
[1,0,1,0,1]

Example 2:

Input: nums = [0,0,0,0,0], goal = 0
Output: 15

 

Constraints:

1 <= nums.length <= 3 * 104

nums[i] is either 0 or 1.

0 <= goal <= nums.length

Generated by CodeBridge
"""

class Solution:
    # def atMost(self, nums, k):
    #     n = len(nums)
    #     count = 0
    #     window = 0

    #     left = 0
    #     for right in range(n):
    #         window += nums[right]

    #         while left <= right and window > k:
    #             window -= nums[left]
    #             left += 1

    #         count += (right - left + 1)

    #     return count

    # def numSubarraysWithSum(self, nums: List[int], goal: int) -> int:
    #     return self.atMost(nums, goal) - self.atMost(nums, goal - 1)

    def numSubarraysWithSum(self, nums: List[int], goal: int) -> int:
        total = 0
        seen = Counter([0])

        prefix = 0
        for num in nums:
            prefix += num
            need = prefix - goal

            total += seen[need]
            seen[need] += 1
            
        return total
        