"""
Title: Pancake Sorting
Difficulty: Medium
Time: 25 min
URL: https://leetcode.com/problems/pancake-sorting/

Given an array of integers arr, sort the array by performing a series of pancake flips.

In one pancake flip we do the following steps:

Choose an integer k where 1 <= k <= arr.length.

Reverse the sub-array arr[0...k-1] (0-indexed).

For example, if arr = [3,2,1,4] and we performed a pancake flip choosing k = 3, we reverse the sub-array [3,2,1], so arr = [1,2,3,4] after the pancake flip at k = 3.

Return an array of the k-values corresponding to a sequence of pancake flips that sort arr. Any valid answer that sorts the array within 10 * arr.length flips will be judged as correct.

 

Example 1:

Input: arr = [3,2,4,1]
Output: [4,2,4,3]
Explanation: 
We perform 4 pancake flips, with k values 4, 2, 4, and 3.
Starting state: arr = [3, 2, 4, 1]
After 1st flip (k = 4): arr = [1, 4, 2, 3]
After 2nd flip (k = 2): arr = [4, 1, 2, 3]
After 3rd flip (k = 4): arr = [3, 2, 1, 4]
After 4th flip (k = 3): arr = [1, 2, 3, 4], which is sorted.

Example 2:

Input: arr = [1,2,3]
Output: []
Explanation: The input is already sorted, so there is no need to flip anything.
Note that other answers, such as [3, 3], would also be accepted.

 

Constraints:

1 <= arr.length <= 100

1 <= arr[i] <= arr.length

All integers in arr are unique (i.e. arr is a permutation of the integers from 1 to arr.length).

Generated by CodeBridge
"""

class Solution:
    def reverse(self, arr, k, index_map):
        left, right = 0, k
        while left < right:
                index_map[arr[left]] = right
                index_map[arr[right]] = left
                arr[left], arr[right] = arr[right], arr[left]

                right -= 1
                left += 1

    def pancakeSort(self, arr: List[int]) -> List[int]:
        n = len(arr)
        index_map = {arr[i] : i for i in range(n)}
        result = []

        # we don't need to do it for 1 
        for num in range(n, 1, -1):
            index = index_map[num]
            # checks if it the number is already placed on it's correct place 
            if index == num - 1:
                continue

            # if the number is already at the front we don't need to reverse to make it at the front
            if index != 0:
                self.reverse(arr, index, index_map)
                result.append(index + 1)
            
            self.reverse(arr, num - 1, index_map)
            result.append(num)

        return result

            

