"""
Title: Subarrays with K Different Integers
Difficulty: Hard
Time: 45 min
URL: https://leetcode.com/problems/subarrays-with-k-different-integers/

Given an integer array nums and an integer k, return the number of good subarrays of nums.

A good array is an array where the number of different integers in that array is exactly k.

For example, [1,2,3,1,2] has 3 different integers: 1, 2, and 3.

A subarray is a contiguous part of an array.

 

Example 1:

Input: nums = [1,2,1,2,3], k = 2
Output: 7
Explanation: Subarrays formed with exactly 2 different integers: [1,2], [2,1], [1,2], [2,3], [1,2,1], [2,1,2], [1,2,1,2]

Example 2:

Input: nums = [1,2,1,3,4], k = 3
Output: 3
Explanation: Subarrays formed with exactly 3 different integers: [1,2,1,3], [2,1,3], [1,3,4].

 

Constraints:

1 <= nums.length <= 2 * 104

1 <= nums[i], k <= nums.length

Generated by CodeBridge
"""

class Solution:
    def subarraysWithAtMostKDistinct(self, nums, k):
        n = len(nums)

        count = 0

        window = Counter()

        left = 0
        for right in range(n):
            window[nums[right]] += 1

            while len(window) > k:
                window[nums[left]] -= 1

                if window[nums[left]] == 0:
                    del window[nums[left]]

                left += 1

            count += (right - left + 1)

        return count

    def subarraysWithKDistinct(self, nums: List[int], k: int) -> int:
        return self.subarraysWithAtMostKDistinct(nums, k) - self.subarraysWithAtMostKDistinct(nums, k - 1)
        