"""
Title: Max Consecutive Ones III
Difficulty: Medium
Time: 10 min
URL: https://leetcode.com/problems/max-consecutive-ones-iii/

Given a binary array nums and an integer k, return the maximum number of consecutive 1's in the array if you can flip at most k 0's.

 

Example 1:

Input: nums = [1,1,1,0,0,0,1,1,1,1,0], k = 2
Output: 6
Explanation: [1,1,1,0,0,1,1,1,1,1,1]
Bolded numbers were flipped from 0 to 1. The longest subarray is underlined.

Example 2:

Input: nums = [0,0,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1], k = 3
Output: 10
Explanation: [0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1]
Bolded numbers were flipped from 0 to 1. The longest subarray is underlined.

 

Constraints:

1 <= nums.length <= 105

nums[i] is either 0 or 1.

0 <= k <= nums.length

Generated by CodeBridge
"""

class Solution:
    def longestOnes(self, nums: List[int], k: int) -> int:
        n = len(nums)
        longest = 0

        window = 0
        left = 0
        for right in range(n):
            if nums[right] == 0:
                window += 1

            while window > k:
                if nums[left] == 0:
                    window -= 1
                left += 1

            longest = max(longest, right - left + 1)

        return longest