"""
# Find Words That Can Be Formed by Characters

**Difficulty:** Easy
**Tags:** Array, Hash Table, String, Counting
**URL:** https://leetcode.com/problems/find-words-that-can-be-formed-by-characters/

## Problem

You are given an array of strings words and a string chars.

A string is good if it can be formed by characters from chars (each character can only be used once for each word in words).

Return the sum of lengths of all good strings in words.

&nbsp;
Example 1:


Input: words = [&quot;cat&quot;,&quot;bt&quot;,&quot;hat&quot;,&quot;tree&quot;], chars = &quot;atach&quot;
Output: 6
Explanation: The strings that can be formed are &quot;cat&quot; and &quot;hat&quot; so the answer is 3 + 3 = 6.


Example 2:


Input: words = [&quot;hello&quot;,&quot;world&quot;,&quot;leetcode&quot;], chars = &quot;welldonehoneyr&quot;
Output: 10
Explanation: The strings that can be formed are &quot;hello&quot; and &quot;world&quot; so the answer is 5 + 5 = 10.


&nbsp;
Constraints:


	1 &lt;= words.length &lt;= 1000
	1 &lt;= words[i].length, chars.length &lt;= 100
	words[i] and chars consist of lowercase English letters.

---
_Generated by CodeBridge_
"""

class Solution:
    def countCharacters(self, words: List[str], chars: str) -> int:
        chars_counts = Counter(chars)
        result = 0

        for i in range(len(words)):
            word_counts = Counter(words[i])

            if all(word_counts[c] <= chars_counts[c] for c in word_counts):
                result += len(words[i])

        return result
