"""
Title: Sort Items by Groups Respecting Dependencies
Difficulty: Hard
Time: 60 min
Attempts: 1
URL: https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/

There are n items each belonging to zero or one of m groups where group[i] is the group that the i-th item belongs to and it's equal to -1 if the i-th item belongs to no group. The items and the groups are zero indexed. A group can have no item belonging to it.

Return a sorted list of the items such that:

The items that belong to the same group are next to each other in the sorted list.

There are some relations between these items where beforeItems[i] is a list containing all the items that should come before the i-th item in the sorted array (to the left of the i-th item).

Return any solution if there is more than one solution and return an empty list if there is no solution.

 

Example 1:

Input: n = 8, m = 2, group = [-1,-1,1,0,0,1,0,-1], beforeItems = [[],[6],[5],[6],[3,6],[],[],[]]
Output: [6,3,4,1,5,2,0,7]

Example 2:

Input: n = 8, m = 2, group = [-1,-1,1,0,0,1,0,-1], beforeItems = [[],[6],[5],[6],[3],[],[4],[]]
Output: []
Explanation: This is the same as example 1 except that 4 needs to be before 6 in the sorted list.

 

Constraints:

1 <= m <= n <= 3 * 104

group.length == beforeItems.length == n

-1 <= group[i] <= m - 1

0 <= beforeItems[i].length <= n - 1

0 <= beforeItems[i][j] <= n - 1

i != beforeItems[i][j]

beforeItems[i] does not contain duplicates elements.

Generated by CodeBridge
"""

class Solution:
    def topSort(self, group):
        order = []

        q = deque()
        
        for e in group:
            if self.indeg[e] == 0:
                q.append(e)
        
        while q:
            v = q.popleft()
            order.append(v)

            for nei in self.graph[v]:
                if self.group[nei] != self.group[v]:
                    continue

                self.indeg[nei] -= 1
                if self.indeg[nei] == 0:
                    q.append(nei)
        
        # impossible to sort if there is cycle
        return order if len(order) == len(group) else []

    def buildGraph(self, beforeItems):
        n = len(beforeItems)
        for i in range(n):
            for pre in beforeItems[i]:
                self.graph[pre].append(i)
                self.indeg[i] += int(self.group[pre] == self.group[i])

    def groupItems(self, groupList, m):
        n = len(groupList)
        groups = [[] for _ in range(m)]

        for i in range(n):
            if groupList[i] == -1:
                groups.append([i])
            else:
                groups[groupList[i]].append(i)

        for gidx, cur_group in enumerate(groups):
            for elem in cur_group:
                self.group[elem] = gidx

        return groups

    def sortItems(
        self, n: int, m: int, group: List[int], beforeItems: List[List[int]]
    ) -> List[int]:
        self.group = group
        self.graph = [[] for _ in range(n)]
        self.indeg = Counter()

        # correctly group elements
        groups = self.groupItems(group, m)

        # building graph
        self.buildGraph(beforeItems)
        
        # build group graphs (condensed graph)
        adj = [[] for _ in range(len(groups))]
        indegree = Counter()

        for gidx, cur_group in enumerate(groups):
            seen = set()

            for elem in cur_group:
                for dep in self.graph[elem]:
                    if self.group[dep] in seen:
                        continue

                    if self.group[dep] == self.group[elem]:
                        continue

                    seen.add(self.group[dep])
                    adj[gidx].append(self.group[dep])
                    indegree[self.group[dep]] += 1

        group_order = []

        q = deque()

        for i in range(len(groups)):
            if indegree[i] == 0:
                q.append(i)

        while q:
            v = q.popleft()
            group_order.append(v)

            for nei in adj[v]:
                indegree[nei] -= 1
                if indegree[nei] == 0:
                    q.append(nei)

        # impossible if there is cycle
        if len(group_order) != len(groups):
            return []

        result = []
        for gidx in group_order:
            if not groups[gidx]:
                continue

            ordered = self.topSort(groups[gidx])

            if not ordered:
                return []

            result.extend(ordered)

        return result
