"""
Title: Count Negative Numbers in a Sorted Matrix
Difficulty: Easy
Time: 20 min
URL: https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/

Given a m x n matrix grid which is sorted in non-increasing order both row-wise and column-wise, return the number of negative numbers in grid.

 

Example 1:

Input: grid = [[4,3,2,-1],[3,2,1,-1],[1,1,-1,-2],[-1,-1,-2,-3]]
Output: 8
Explanation: There are 8 negatives number in the matrix.

Example 2:

Input: grid = [[3,2],[1,0]]
Output: 0

 

Constraints:

m == grid.length

n == grid[i].length

1 <= m, n <= 100

-100 <= grid[i][j] <= 100

 
Follow up: Could you find an O(n + m) solution?

Generated by CodeBridge
"""

class Solution:
    def countNegatives(self, grid: List[List[int]]) -> int:
        cols = len(grid[0])

        count = 0
        for row in grid:
            left, right = 0, len(row) - 1

            while left <= right:
                mid = (left + right) // 2

                if row[mid] >= 0:
                    left = mid + 1
                else:
                    right = mid - 1

            if -1 < left < cols:
                count += (cols - left)

        return count