"""
Title: Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit
Difficulty: Medium
Time: 20 min
URL: https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/

Given an array of integers nums and an integer limit, return the size of the longest non-empty subarray such that the absolute difference between any two elements of this subarray is less than or equal to limit.

 

Example 1:

Input: nums = [8,2,4,7], limit = 4
Output: 2 
Explanation: All subarrays are: 
[8] with maximum absolute diff |8-8| = 0 <= 4.
[8,2] with maximum absolute diff |8-2| = 6 > 4. 
[8,2,4] with maximum absolute diff |8-2| = 6 > 4.
[8,2,4,7] with maximum absolute diff |8-2| = 6 > 4.
[2] with maximum absolute diff |2-2| = 0 <= 4.
[2,4] with maximum absolute diff |2-4| = 2 <= 4.
[2,4,7] with maximum absolute diff |2-7| = 5 > 4.
[4] with maximum absolute diff |4-4| = 0 <= 4.
[4,7] with maximum absolute diff |4-7| = 3 <= 4.
[7] with maximum absolute diff |7-7| = 0 <= 4. 
Therefore, the size of the longest subarray is 2.

Example 2:

Input: nums = [10,1,2,4,7,2], limit = 5
Output: 4 
Explanation: The subarray [2,4,7,2] is the longest since the maximum absolute diff is |2-7| = 5 <= 5.

Example 3:

Input: nums = [4,2,2,2,4,4,2,2], limit = 0
Output: 3

 

Constraints:

1 <= nums.length <= 105

1 <= nums[i] <= 109

0 <= limit <= 109

Generated by CodeBridge
"""

class Solution:
    def longestSubarray(self, nums: List[int], limit: int) -> int:
        min_deque = deque()
        max_deque = deque()
        n = len(nums)

        longest = 0
        
        left = 0
        for right in range(n):
            num = nums[right]

            while min_deque and min_deque[-1] > num:
                min_deque.pop()

            min_deque.append(num)

            while max_deque and max_deque[-1] < num:
                max_deque.pop()

            max_deque.append(num)

            while max_deque[0] - min_deque[0] > limit:
                if min_deque[0] == nums[left]:
                    min_deque.popleft()
                
                if max_deque[0] == nums[left]:
                    max_deque.popleft()

                left += 1

            longest = max(longest, right - left + 1)

        return longest

