"""
Title: Determine if Two Strings Are Close
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/determine-if-two-strings-are-close/

Two strings are considered close if you can attain one from the other using the following operations:

Operation 1: Swap any two existing characters.

For example, abcde -> aecdb

Operation 2: Transform every occurrence of one existing character into another existing character, and do the same with the other character.

For example, aacabb -> bbcbaa (all a's turn into b's, and all b's turn into a's)

You can use the operations on either string as many times as necessary.

Given two strings, word1 and word2, return true if word1 and word2 are close, and false otherwise.

 

Example 1:

Input: word1 = "abc", word2 = "bca"
Output: true
Explanation: You can attain word2 from word1 in 2 operations.
Apply Operation 1: "abc" -> "acb"
Apply Operation 1: "acb" -> "bca"

Example 2:

Input: word1 = "a", word2 = "aa"
Output: false
Explanation: It is impossible to attain word2 from word1, or vice versa, in any number of operations.

Example 3:

Input: word1 = "cabbba", word2 = "abbccc"
Output: true
Explanation: You can attain word2 from word1 in 3 operations.
Apply Operation 1: "cabbba" -> "caabbb"
Apply Operation 2: "caabbb" -> "baaccc"
Apply Operation 2: "baaccc" -> "abbccc"

 

Constraints:

1 <= word1.length, word2.length <= 105

word1 and word2 contain only lowercase English letters.

Generated by CodeBridge
"""

class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        # strings are close if
        # 1, they have equal length
        # 2, they contain same characters
        # 3, the multiset of their character frequencies is identical
        # (since it is allowed to swap the characters themselves)

        if len(word1) != len(word2):
            return False

        count1 = Counter(word1)
        count2 = Counter(word2)
        
        # this counter will track the how many times the word2's characters' frequency appears
        # it will allow us to check
        # if the multiset of the character frequencies of the words match
        freq_counter = Counter()

        # this checks, if all chars of word2 are in word1
        # at the same time we also count the appearance of the frequencies of
        # word2 chars' frequency 
        for char, freq in count2.items():
            if char not in count1:
                return False
            freq_counter[freq] += 1

        # for each character in word1
        # - it should exist in word2
        # - its frequency should appear as one of word2 character's frequency 
        for char, freq in count1.items():
            if char not in count2:
                return False
 
            if freq not in freq_counter:
                return False

            # decrement the matched frequency
            freq_counter[freq] -= 1

            if freq_counter[freq] == 0:
                del freq_counter[freq]

        return  True