"""
Title: Determine if Two Strings Are Close
Difficulty: Medium
Time: 25 min
URL: https://leetcode.com/problems/determine-if-two-strings-are-close/

Two strings are considered close if you can attain one from the other using the following operations:

Operation 1: Swap any two existing characters.

For example, abcde -> aecdb

Operation 2: Transform every occurrence of one existing character into another existing character, and do the same with the other character.

For example, aacabb -> bbcbaa (all a's turn into b's, and all b's turn into a's)

You can use the operations on either string as many times as necessary.

Given two strings, word1 and word2, return true if word1 and word2 are close, and false otherwise.

 

Example 1:

Input: word1 = "abc", word2 = "bca"
Output: true
Explanation: You can attain word2 from word1 in 2 operations.
Apply Operation 1: "abc" -> "acb"
Apply Operation 1: "acb" -> "bca"

Example 2:

Input: word1 = "a", word2 = "aa"
Output: false
Explanation: It is impossible to attain word2 from word1, or vice versa, in any number of operations.

Example 3:

Input: word1 = "cabbba", word2 = "abbccc"
Output: true
Explanation: You can attain word2 from word1 in 3 operations.
Apply Operation 1: "cabbba" -> "caabbb"
Apply Operation 2: "caabbb" -> "baaccc"
Apply Operation 2: "baaccc" -> "abbccc"

 

Constraints:

1 <= word1.length, word2.length <= 105

word1 and word2 contain only lowercase English letters.

Generated by CodeBridge
"""

class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        # if their length doesn't match we can't  make them equal
        if len(word1) != len(word2):
            return False

        # stores the frequency of each character in the strings
        count1 = Counter(word1)
        count2 = Counter(word2)
        # stores the occurence (frequency) of the those frequencies
        counts = Counter()

        for key, count in count2.items():
            # if the character isn't found on the other string, we can't make them equal
            if key not in count1:
                return False
            counts[count] += 1

        for key, count in count1.items():
            # if the character isn't found on the other string, we can't make them equal
            if key not in count1:
                return False

            if count not in counts:
                return False

            counts[count] -= 1

            if counts[count] == 0:
                del counts[count]

        return  True