"""
Title: Check if Binary String Has at Most One Segment of Ones
Difficulty: Easy
Time: 5 min
URL: https://leetcode.com/problems/check-if-binary-string-has-at-most-one-segment-of-ones/

Given a binary string s ​​​​​without leading zeros, return true​​​ if s contains at most one contiguous segment of ones. Otherwise, return false.

 

Example 1:

Input: s = "1001"
Output: false
Explanation: The string has two segments of size 1.

Example 2:

Input: s = "110"
Output: true

 

Constraints:

1 <= s.length <= 100

s[i]​​​​ is either '0' or '1'.

s[0] is '1'.

Generated by CodeBridge
"""

class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        first_index = s.find("1")
        last_index = s.rfind("1")
        k = s.count("1")

        if first_index + k - 1== last_index:
            return True

        return False
