"""
Title: Determine Whether Matrix Can Be Obtained By Rotation
Difficulty: Easy
Time: 30 min
URL: https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/

Given two n x n binary matrices mat and target, return true if it is possible to make mat equal to target by rotating mat in 90-degree increments, or false otherwise.

 

Example 1:

Input: mat = [[0,1],[1,0]], target = [[1,0],[0,1]]
Output: true
Explanation: We can rotate mat 90 degrees clockwise to make mat equal target.

Example 2:

Input: mat = [[0,1],[1,1]], target = [[1,0],[0,1]]
Output: false
Explanation: It is impossible to make mat equal to target by rotating mat.

Example 3:

Input: mat = [[0,0,0],[0,1,0],[1,1,1]], target = [[1,1,1],[0,1,0],[0,0,0]]
Output: true
Explanation: We can rotate mat 90 degrees clockwise two times to make mat equal target.

 

Constraints:

n == mat.length == target.length

n == mat[i].length == target[i].length

1 <= n <= 10

mat[i][j] and target[i][j] are either 0 or 1.

Generated by CodeBridge
"""

class Solution:
    def rotate(self, matrix):
        n = len(matrix)
        for i in range(n):
            for j in range(i + 1, n):
                matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

        for row in matrix:
            i, j = 0, n - 1
            while i < j:
                row[i], row[j] = row[j], row[i]

                i += 1
                j -= 1

    def checkEqual(self, mat1, mat2):
        n = len(mat1)

        for i in range(n):
            for j in range(n):
                if mat1[i][j] != mat2[i][j]:
                    return False

        return True

    def findRotation(self, mat: List[List[int]], target: List[List[int]]) -> bool:
        n = len(mat)

        for _ in range(4):
            if self.checkEqual(mat, target):
                return True
            self.rotate(mat)

        return False