"""
Title: Count Vowel Substrings of a String
Difficulty: Easy
Time: 15 min
URL: https://leetcode.com/problems/count-vowel-substrings-of-a-string/

A substring is a contiguous (non-empty) sequence of characters within a string.

A vowel substring is a substring that only consists of vowels ('a', 'e', 'i', 'o', and 'u') and has all five vowels present in it.

Given a string word, return the number of vowel substrings in word.

 

Example 1:

Input: word = "aeiouu"
Output: 2
Explanation: The vowel substrings of word are as follows (underlined):
- "aeiouu"
- "aeiouu"

Example 2:

Input: word = "unicornarihan"
Output: 0
Explanation: Not all 5 vowels are present, so there are no vowel substrings.

Example 3:

Input: word = "cuaieuouac"
Output: 7
Explanation: The vowel substrings of word are as follows (underlined):
- "cuaieuouac"
- "cuaieuouac"
- "cuaieuouac"
- "cuaieuouac"
- "cuaieuouac"
- "cuaieuouac"
- "cuaieuouac"

 

Constraints:

1 <= word.length <= 100

word consists of lowercase English letters only.

Generated by CodeBridge
"""

class Solution:
    def __init__(self):
        self.vowels =set("aeiou")

    def atMost(self, word, k):
        count = 0
        window = Counter()
        
        left = 0
        for right, value in enumerate(word):
            if value not in self.vowels:
                left = right + 1
                window.clear()
                continue
            
            window[value] += 1

            while len(window) > k:
                char = word[left]
                window[char] -= 1

                if window[char] == 0:
                    del window[char]
                left += 1

            count += (right - left + 1)

        return count


    def countVowelSubstrings(self, word: str) -> int:
        k = len(self.vowels)
        return self.atMost(word, k) - self.atMost(word, k - 1)