"""
Title: Detonate the Maximum Bombs
Difficulty: Medium
Time: 60 min
URL: https://leetcode.com/problems/detonate-the-maximum-bombs/

You are given a list of bombs. The range of a bomb is defined as the area where its effect can be felt. This area is in the shape of a circle with the center as the location of the bomb.

The bombs are represented by a 0-indexed 2D integer array bombs where bombs[i] = [xi, yi, ri]. xi and yi denote the X-coordinate and Y-coordinate of the location of the ith bomb, whereas ri denotes the radius of its range.

You may choose to detonate a single bomb. When a bomb is detonated, it will detonate all bombs that lie in its range. These bombs will further detonate the bombs that lie in their ranges.

Given the list of bombs, return the maximum number of bombs that can be detonated if you are allowed to detonate only one bomb.

 

Example 1:

Input: bombs = [[2,1,3],[6,1,4]]
Output: 2
Explanation:
The above figure shows the positions and ranges of the 2 bombs.
If we detonate the left bomb, the right bomb will not be affected.
But if we detonate the right bomb, both bombs will be detonated.
So the maximum bombs that can be detonated is max(1, 2) = 2.

Example 2:

Input: bombs = [[1,1,5],[10,10,5]]
Output: 1
Explanation:
Detonating either bomb will not detonate the other bomb, so the maximum number of bombs that can be detonated is 1.

Example 3:

Input: bombs = [[1,2,3],[2,3,1],[3,4,2],[4,5,3],[5,6,4]]
Output: 5
Explanation:
The best bomb to detonate is bomb 0 because:
- Bomb 0 detonates bombs 1 and 2. The red circle denotes the range of bomb 0.
- Bomb 2 detonates bomb 3. The blue circle denotes the range of bomb 2.
- Bomb 3 detonates bomb 4. The green circle denotes the range of bomb 3.
Thus all 5 bombs are detonated.

 

Constraints:

1 <= bombs.length <= 100

bombs[i].length == 3

1 <= xi, yi, ri <= 105

Generated by CodeBridge
"""

class Solution:
    def maximumDetonation(self, bombs: List[List[int]]) -> int:
        n = len(bombs)

        def in_range(circle, point):
            i, j, _ = point
            x, y, r = circle

            return ((x - i) ** 2 + (y - j) ** 2) ** 0.5 <= r

        adj = [[] for _ in range(n)]

        # build graph
        for i in range(n): 
            for j in range(n):
                if i == j: continue
                if in_range(bombs[i], bombs[j]):
                    adj[i].append(j)

        
        def dfs(vertex, visited):
            vertices = 0

            for nei in adj[vertex]:
                if not visited[nei]:
                    visited[nei] = True
                    vertices += dfs(nei, visited)

            return 1 + vertices

        maxx = 0

        for vertex in range(n):
            visited = [False] * n

            visited[vertex] = True
            maxx = max(maxx, dfs(vertex, visited))

        return maxx
            