"""
Title: Remove Nodes From Linked List
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/remove-nodes-from-linked-list/

You are given the head of a linked list.

Remove every node which has a node with a greater value anywhere to the right side of it.

Return the head of the modified linked list.

 

Example 1:

Input: head = [5,2,13,3,8]
Output: [13,8]
Explanation: The nodes that should be removed are 5, 2 and 3.
- Node 13 is to the right of node 5.
- Node 13 is to the right of node 2.
- Node 8 is to the right of node 3.

Example 2:

Input: head = [1,1,1,1]
Output: [1,1,1,1]
Explanation: Every node has value 1, so no nodes are removed.

 

Constraints:

The number of the nodes in the given list is in the range [1, 105].

1 <= Node.val <= 105

Generated by CodeBridge
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def reverse(self, head):
        prev = None
        cur = head

        while cur:
            next = cur.next
            cur.next = prev
            prev = cur
            cur = next

        return prev
        
    def removeNodes(self, head: Optional[ListNode]) -> Optional[ListNode]:
        stack = ListNode(0)

        itr = head

        while itr:
            while stack.next and stack.next.val < itr.val:
                stack.next = stack.next.next

            temp = itr.next
            itr.next = stack.next
            stack.next = itr

            itr = temp

        return self.reverse(stack.next)

# # Definition for singly-linked list.
# # class ListNode:
# #     def __init__(self, val=0, next=None):
# #         self.val = val
# #         self.next = next
# class Solution:
#     def removeNodes(self, head: Optional[ListNode]) -> Optional[ListNode]:
#         stack = []

#         itr = head
#         while itr:
#             while stack and stack[-1].val < itr.val:
#                 stack.pop()

#             stack.append(itr)

#             itr = itr.next

#         for i in range(len(stack) - 1):
#             stack[i].next = stack[i + 1]
            
#         stack[-1].next = None

#         return stack[0]