"""
Title: Count Anagrams
Difficulty: Hard
Time: 120 min
URL: https://leetcode.com/problems/count-anagrams/

You are given a string s containing one or more words. Every consecutive pair of words is separated by a single space ' '.

A string t is an anagram of string s if the ith word of t is a permutation of the ith word of s.

For example, "acb dfe" is an anagram of "abc def", but "def cab" and "adc bef" are not.

Return the number of distinct anagrams of s. Since the answer may be very large, return it modulo 109 + 7.

 

Example 1:

Input: s = "too hot"
Output: 18
Explanation: Some of the anagrams of the given string are "too hot", "oot hot", "oto toh", "too toh", and "too oht".

Example 2:

Input: s = "aa"
Output: 1
Explanation: There is only one anagram possible for the given string.

 

Constraints:

1 <= s.length <= 105

s consists of lowercase English letters and spaces ' '.

There is single space between consecutive words.

Generated by CodeBridge
"""

class Solution:
    def __init__(self):
        MAX_INT = 10 ** 5
        self.mod = 10 ** 9 + 7
        self.compute_factorials(MAX_INT)

    def compute_factorials(self, MAX_INT):
        # contains moded factorials
        self.factorials = [1] * (MAX_INT + 1)
        self.inverse_factorials = [1] * (MAX_INT + 1)

        for i in range(1, MAX_INT + 1):
            # i is already less than m
            # the previous factorial is also already moded
            self.factorials[i] = (i * self.factorials[i - 1]) % self.mod

        self.inverse_factorials[MAX_INT] = pow(self.factorials[MAX_INT], self.mod - 2, self.mod) # this has O(log n)
        # compute the inverse of the factorials starting from the back 
        for i in range(MAX_INT - 1, -1, -1):
            # this computes the modular inverse of the current factorial based on the modular inverse of the previously computes factorial
            # KNOWN FORMULA: mod_inv(i) = (mod_inv(i + 1) * (i + 1)) mod m -- more in the note
            self.inverse_factorials[i] = (self.inverse_factorials[i + 1] * (i + 1)) % self.mod

    def permutation(self, word):
        n = len(word)
        counts = Counter(word)

        result = self.factorials[n]
        for count in counts.values():
            # both values are already moded, so they are smaller 
            # this one is another trick too (written on the note)
            result = (result * self.inverse_factorials[count]) % self.mod

        return  result

    def countAnagrams(self, s: str) -> int:
        total_count = 1
        for word in s.split():
            # both values are already moded, so they are smaller 
            total_count = (total_count * self.permutation(word)) % self.mod

        return total_count
