"""
# Count Anagrams

**Difficulty:** Hard
**Tags:** Hash Table, Math, String, Combinatorics, Counting
**URL:** https://leetcode.com/problems/count-anagrams/

## Problem

You are given a string s containing one or more words. Every consecutive pair of words is separated by a single space &#39; &#39;.

A string t is an anagram of string s if the ith word of t is a permutation of the ith word of s.


	For example, &quot;acb dfe&quot; is an anagram of &quot;abc def&quot;, but &quot;def cab&quot;&nbsp;and &quot;adc bef&quot; are not.


Return the number of distinct anagrams of s. Since the answer may be very large, return it modulo 109 + 7.

&nbsp;
Example 1:


Input: s = &quot;too hot&quot;
Output: 18
Explanation: Some of the anagrams of the given string are &quot;too hot&quot;, &quot;oot hot&quot;, &quot;oto toh&quot;, &quot;too toh&quot;, and &quot;too oht&quot;.


Example 2:


Input: s = &quot;aa&quot;
Output: 1
Explanation: There is only one anagram possible for the given string.

&nbsp;
Constraints:


	1 &lt;= s.length &lt;= 105
	s consists of lowercase English letters and spaces &#39; &#39;.
	There is single space between consecutive words.

---
_Generated by CodeBridge_
"""

class Solution:
    def __init__(self):
        self.memo = {}

    def factorial(self, n):
        if n <=  1:
            return 1

        if n in self.memo:
            return self.memo[n]

        return n * self.factorial(n - 1)

    def permutation(self, word):
        n = len(word)
        counts = Counter(word)
        n_factorial = factorial(n)
        freq_factorial = 1

        for count in counts.values():
            count_factorial = factorial(count)
            freq_factorial *= count_factorial
            self.memo[count] = count_factorial

        self.memo[n] = n_factorial

        return n_factorial // freq_factorial

    def countAnagrams(self, s: str) -> int:
        total_count = 1
        for word in s.split():
            total_count = (total_count * self.permutation(word)) % (10 ** 9 + 7)

        return total_count