"""
Title: Count Complete Subarrays in an Array
Difficulty: Medium
Time: 10 min
URL: https://leetcode.com/problems/count-complete-subarrays-in-an-array/?envType=problem-list-v2&envId=sliding-window

You are given an array nums consisting of positive integers.

We call a subarray of an array complete if the following condition is satisfied:

The number of distinct elements in the subarray is equal to the number of distinct elements in the whole array.

Return the number of complete subarrays.

A subarray is a contiguous non-empty part of an array.

 

Example 1:

Input: nums = [1,3,1,2,2]
Output: 4
Explanation: The complete subarrays are the following: [1,3,1,2], [1,3,1,2,2], [3,1,2] and [3,1,2,2].

Example 2:

Input: nums = [5,5,5,5]
Output: 10
Explanation: The array consists only of the integer 5, so any subarray is complete. The number of subarrays that we can choose is 10.

 

Constraints:

1 <= nums.length <= 1000

1 <= nums[i] <= 2000

Generated by CodeBridge
"""

class Solution:
    def atMost(self, nums, k):
        count = 0

        window = defaultdict(int)

        left = 0
        for right, value in enumerate(nums):
            window[value] += 1

            while left <= right and len(window) > k:
                window[nums[left]] -= 1
                
                if window[nums[left]] == 0:
                    del window[nums[left]]
                left += 1

            count += (right - left + 1)

        return count

    def countCompleteSubarrays(self, nums: List[int]) -> int:
        k = len(set(nums))

        return self.atMost(nums, k) - self.atMost(nums, k - 1)
