"""
Title: Minimum Index of a Valid Split
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/minimum-index-of-a-valid-split/

An element x of an integer array arr of length m is dominant if more than half the elements of arr have a value of x.

You are given a 0-indexed integer array nums of length n with one dominant element.

You can split nums at an index i into two arrays nums[0, ..., i] and nums[i + 1, ..., n - 1], but the split is only valid if:

0 <= i < n - 1

nums[0, ..., i], and nums[i + 1, ..., n - 1] have the same dominant element.

Here, nums[i, ..., j] denotes the subarray of nums starting at index i and ending at index j, both ends being inclusive. Particularly, if j < i then nums[i, ..., j] denotes an empty subarray.

Return the minimum index of a valid split. If no valid split exists, return -1.

 

Example 1:

Input: nums = [1,2,2,2]
Output: 2
Explanation: We can split the array at index 2 to obtain arrays [1,2,2] and [2]. 
In array [1,2,2], element 2 is dominant since it occurs twice in the array and 2 * 2 > 3. 
In array [2], element 2 is dominant since it occurs once in the array and 1 * 2 > 1.
Both [1,2,2] and [2] have the same dominant element as nums, so this is a valid split. 
It can be shown that index 2 is the minimum index of a valid split. 

Example 2:

Input: nums = [2,1,3,1,1,1,7,1,2,1]
Output: 4
Explanation: We can split the array at index 4 to obtain arrays [2,1,3,1,1] and [1,7,1,2,1].
In array [2,1,3,1,1], element 1 is dominant since it occurs thrice in the array and 3 * 2 > 5.
In array [1,7,1,2,1], element 1 is dominant since it occurs thrice in the array and 3 * 2 > 5.
Both [2,1,3,1,1] and [1,7,1,2,1] have the same dominant element as nums, so this is a valid split.
It can be shown that index 4 is the minimum index of a valid split.

Example 3:

Input: nums = [3,3,3,3,7,2,2]
Output: -1
Explanation: It can be shown that there is no valid split.

 

Constraints:

1 <= nums.length <= 105

1 <= nums[i] <= 109

nums has exactly one dominant element.

Generated by CodeBridge
"""

class Solution:
    def minimumIndex(self, nums: List[int]) -> int:
        leng = len(nums)
        counts = Counter(nums)
        dom = max(counts, key=lambda x: counts[x])

        # total_count of dom
        total_count = counts[dom]
        # left subarray count of dom
        left_count = 0

        for i in range(leng):
            if nums[i] == dom:
                left_count += 1

            left_size = i + 1
            right_size = leng - left_size
            right_count = total_count - left_count

            # if dom is dominant on both left and right side 
            if left_count > left_size // 2 and right_count > right_size // 2:
                return i

        return -1