"""
Title: Find the Most Common Response
Difficulty: Medium
Time: 15 min
URL: https://leetcode.com/problems/find-the-most-common-response/

You are given a 2D string array responses where each responses[i] is an array of strings representing survey responses from the ith day.

Return the most common response across all days after removing duplicate responses within each responses[i]. If there is a tie, return the lexicographically smallest response.

 

Example 1:

Input: responses = [["good","ok","good","ok"],["ok","bad","good","ok","ok"],["good"],["bad"]]

Output: "good"

Explanation:

After removing duplicates within each list, responses = [["good", "ok"], ["ok", "bad", "good"], ["good"], ["bad"]].

"good" appears 3 times, "ok" appears 2 times, and "bad" appears 2 times.

Return "good" because it has the highest frequency.

Example 2:

Input: responses = [["good","ok","good"],["ok","bad"],["bad","notsure"],["great","good"]]

Output: "bad"

Explanation:

After removing duplicates within each list we have responses = [["good", "ok"], ["ok", "bad"], ["bad", "notsure"], ["great", "good"]].

"bad", "good", and "ok" each occur 2 times.

The output is "bad" because it is the lexicographically smallest amongst the words with the highest frequency.

 

Constraints:

1 <= responses.length <= 1000

1 <= responses[i].length <= 1000

1 <= responses[i][j].length <= 10

responses[i][j] consists of only lowercase English letters

Generated by CodeBridge
"""

class Solution:
    def findCommonResponse(self, responses: List[List[str]]) -> str:
        counts = Counter()

        for day_responses in responses:
            seen = set()

            for response in day_responses:
                if response not in seen:
                    counts[response] += 1
                    seen.add(response)

        most_common = responses[0][0]

        # finds the response with highest frequency, if tie find the smallest one of them 
        for response, count in counts.items():
            if count > counts[most_common]:
                most_common = response
            elif count == counts[most_common] and response < most_common:
                most_common = response

        return most_common
        