"""
Title: Dominant Character
Difficulty: 1400
Time: 120 min
URL: https://codeforces.com/problemset/problem/1605/C

Ashish has a string  of length  containing only characters 'a', 'b' and 'c'.
He wants to find the length of the smallest substring, which satisfies the following conditions:  
 Length of the substring is at least  
 'a' occurs strictly more times in this substring than 'b' 
 'a' occurs strictly more times in this substring than 'c'  
Ashish is busy planning his next Codeforces round. Help him solve the problem.
A string  is a substring of a string  if  can be obtained from  by deletion of several (possibly, zero or all) characters from the beginning and several (possibly, zero or all) characters from the end.

Input
The first line contains a single integer    — the number of test cases. The description of test cases follows.
The first line of each test case contains a single integer    — the length of the string .
The second line of each test case contains a string  consisting only of characters 'a', 'b' and 'c'.
It is guaranteed that the sum of  over all test cases does not exceed .

Output
For each test case, output the length of the smallest substring which satisfies the given conditions or print  if there is no such substring.

Example

3
2
aa
5
cbabb
8
cacabccc

2
-1
3

Note
Consider the first test case. In the substring "aa", 'a' occurs twice, while 'b' and 'c' occur zero times. Since 'a' occurs strictly more times than 'b' and 'c', the substring "aa" satisfies the condition and the answer is . The substring "a" also satisfies this condition, however its length is not at least .
In the second test case, it can be shown that in none of the substrings of "cbabb" does 'a' occur strictly more times than 'b' and 'c' each.
In the third test case, "cacabccc", the length of the smallest substring that satisfies the conditions is .

Generated by CodeBridge
"""

for _ in range(int(input())):
    n = int(input())
    s = input()


    possible_values = ["aa", "aba", "aca", "abca", "acba", "abbacca", "accabba"]
    
    for value in possible_values:
        if value in s:
            print(len(value))
            break
        
    else:
        print(-1)
