"""
Title: Phoenix and Socks
Difficulty: 1500
Time: 120 min
URL: https://codeforces.com/contest/1515/problem/D

To satisfy his love of matching socks, Phoenix has brought his $n$ socks ($n$ is even) to the sock store. Each of his socks has a color $c_i$ and is either a left sock or right sock. 
Phoenix can pay one dollar to the sock store to either:  
 recolor a sock to any color $c'$ $(1 \le c' \le n)$ 
 turn a left sock into a right sock 
 turn a right sock into a left sock  
The sock store may perform each of these changes any number of times. Note that the color of a left sock doesn't change when it turns into a right sock, and vice versa. 
A matching pair of socks is a left and right sock with the same color. What is the minimum cost for Phoenix to make $n/2$ matching pairs? Each sock must be included in exactly one matching pair.

Input
The input consists of multiple test cases. The first line contains an integer $t$ ($1 \le t \le 1000$) — the number of test cases.
The first line of each test case contains three integers $n$, $l$, and $r$ ($2 \le n \le 2 \cdot 10^5$; $n$ is even; $0 \le l, r \le n$; $l+r=n$) — the total number of socks, and the number of left and right socks, respectively.
The next line contains $n$ integers $c_i$ ($1 \le c_i \le n$) — the colors of the socks. The first $l$ socks are left socks, while the next $r$ socks are right socks.
It is guaranteed that the sum of $n$ across all the test cases will not exceed $2 \cdot 10^5$.

Output
For each test case, print one integer — the minimum cost for Phoenix to make $n/2$ matching pairs. Each sock must be included in exactly one matching pair.

Example

4
6 3 3
1 2 3 2 2 2
6 2 4
1 1 2 2 2 2
6 5 1
6 5 4 3 2 1
4 0 4
4 4 4 3

2
3
5
3

Note
In the first test case, Phoenix can pay $2$ dollars to:  
 recolor sock $1$ to color $2$ 
 recolor sock $3$ to color $2$  There are now $3$ matching pairs. For example, pairs $(1, 4)$, $(2, 5)$, and $(3, 6)$ are matching.
In the second test case, Phoenix can pay $3$ dollars to:  
 turn sock $6$ from a right sock to a left sock 
 recolor sock $3$ to color $1$ 
 recolor sock $4$ to color $1$  There are now $3$ matching pairs. For example, pairs $(1, 3)$, $(2, 4)$, and $(5, 6)$ are matching.

Generated by CodeBridge
"""

from collections import Counter
for _ in range(int(input())):
    n, l, r = list(map(int, input().split()))
    arr = list(map(int, input().split()))
    left, right = arr[:l], arr[l:]
    
    if l < r:
        left, right = right, left
        l, r = r, l
    
    left_counts = Counter(left)
    right_counts = Counter(right)
    
    op_count = 0
    
    required_transfer = (l - r) // 2
    op_count = required_transfer
    
    # balancing
    for num in left_counts:
        if required_transfer == 0:
            break
        
        transfer = int((left_counts[num] - right_counts[num]) / 2)
        
        if transfer < 0:
            continue
        
        transfer = min(required_transfer, abs(transfer))
        
        left_counts[num] -= transfer
        right_counts[num] += transfer
        
        required_transfer -= abs(transfer)
    
    for num in left_counts:
        minn = min(left_counts[num], right_counts[num])
        left_counts[num] -= minn
        right_counts[num] -= minn
        
        
    left_count_sum = sum(left_counts.values())
    right_count_sum = sum(right_counts.values())
    color_changes = (left_count_sum + right_count_sum) // 2
    
    op_count += color_changes
    
    print(op_count)
 
    
    