"""
# Short Sort

**Difficulty:** 800
**Tags:** brute force, implementation, 800
**URL:** https://codeforces.com/contest/1873/problem/A

## Problem

There are three cards with letters , ,  placed in a row in some order. You can do the following operation at most once:  
 Pick two cards, and swap them.  Is it possible that the row becomes  after the operation? Output "YES" if it is possible, and "NO" otherwise.

Input
The first line contains a single integer  ()&nbsp;— the number of test cases.
The only line of each test case contains a single string consisting of each of the three characters , , and  exactly once, representing the cards.

Output
For each test case, output "YES" if you can make the row  with at most one operation, or "NO" otherwise.
You can output the answer in any case (for example, the strings "yEs", "yes", "Yes" and "YES" will be recognized as a positive answer).

Example

6
abc
acb
bac
bca
cab
cba

YES
YES
YES
NO
NO
YES

Note
In the first test case, we don't need to do any operations, since the row is already .
In the second test case, we can swap  and : .
In the third test case, we can swap  and : .
In the fourth test case, it is impossible to make  using at most one operation.

---
_Generated by CodeBridge_
"""

