"""
Title: Array Splitting
Difficulty: 1400
Time: 60 mini
URL: https://codeforces.com/problemset/problem/1197/C

You are given a sorted array $a_1, a_2, \dots, a_n$ (for each index $i  \gt  1$ condition $a_i \ge a_{i-1}$ holds) and an integer $k$.
You are asked to divide this array into $k$ non-empty consecutive subarrays. Every element in the array should be included in exactly one subarray. 
Let $max(i)$ be equal to the maximum in the $i$-th subarray, and $min(i)$ be equal to the minimum in the $i$-th subarray. The cost of division is equal to $\sum\limits_{i=1}^{k} (max(i) - min(i))$. For example, if $a = [2, 4, 5, 5, 8, 11, 19]$ and we divide it into $3$ subarrays in the following way: $[2, 4], [5, 5], [8, 11, 19]$, then the cost of division is equal to $(4 - 2) + (5 - 5) + (19 - 8) = 13$.
Calculate the minimum cost you can obtain by dividing the array $a$ into $k$ non-empty consecutive subarrays. 

Input
The first line contains two integers $n$ and $k$ ($1 \le k \le n \le 3 \cdot 10^5$).
The second line contains $n$ integers $a_1, a_2, \dots, a_n$ ($ 1 \le a_i \le 10^9$, $a_i \ge a_{i-1}$). 

Output
Print the minimum cost you can obtain by dividing the array $a$ into $k$ nonempty consecutive subarrays. 

Examples

6 3
4 8 15 16 23 42

12

4 4
1 3 3 7

0

8 1
1 1 2 3 5 8 13 21

20

Note
In the first test we can divide array $a$ in the following way: $[4, 8, 15, 16], [23], [42]$.

Generated by CodeBridge
"""

44721 44000
1 10743 54125 84909 114013 122595 127229 144445 180720 209841 221654 258157 282944 288518 309758 314664 355261 389136 411117 453015 468991 505631 511067 512303 522796 548531 582336 599087 641852 684656 725602 728208 762344 762862 804271 818443 856846 871612 887195 901805 941134 976570 984791 1009674 1039496 1065130 1100973 1110056 1113216 1126301 1165337 1168524 1182958 1214376 1224501 1250470 1263483 1271426 1285776 1301010 1309474 1327757 1350908 1385578 1392777 1407334 1425622 1461521 15033...