"""
Title: Divisible Permutation
Difficulty: 800
Time: 10 min
URL: https://codeforces.com/contest/2188/problem/A

You are given an integer $n$. Construct a permutation$^{\text{∗}}$ $p$ of length $n$ satisfying the following condition: 
 $\lvert p_i - p_{i+1} \rvert$ is divisible by $i$ for every $1 \le i \le n-1$. 
It can be proven that such a permutation always exists under the constraints of the problem.

$^{\text{∗}}$A permutation of length $n$ is an array consisting of $n$ distinct integers from $1$ to $n$ in arbitrary order. For example, $[2,3,1,5,4]$ is a permutation, but $[1,2,2]$ is not a permutation ($2$ appears twice in the array), and $[1,3,4]$ is also not a permutation ($n=3$ but there is $4$ in the array). 

Input
Each test contains multiple test cases. The first line contains the number of test cases $t$ ($1 \le t \le 100$). The description of the test cases follows. 
The only line of each test case contains a single integer $n$ ($2 \le n \le 100$) — the length of the permutation $p$ to be constructed.

Output
For each test case, output $n$ integers $p_1,p_2,\ldots,p_n$ ($1 \le p_i \le n$, all $p_i$-s are distinct) — the permutation you constructed.
If there are multiple valid permutations, you may output any of them.

Example

2
2
3

1 2
2 3 1

Note
In the first test case, $p=[1,2]$ satisfies the condition because $\lvert p_1-p_2\rvert=\lvert 1-2\rvert=1$, which is divisible by $1$.
In the second test case, $p=[2,3,1]$ satisfies the condition because: 
 $\lvert p_1-p_2\rvert=\lvert 2-3\rvert=1$, which is divisible by $1$, and 
 $\lvert p_2-p_3\rvert=\lvert 3-1\rvert=2$, which is divisible by $2$.

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution():
    n = read_int()
    
    result = [0] * n
    
    i = 1 - (n % 2)
    for num in range(n//2 + 1, n + 1):
        result[i] = num
        i += 2
    
    i = n % 2
    for num in range(n // 2, 0, -1):
        result[i] = num
        i += 2
        
 
    print(*result)
 
 
def main():
    t = 1
    t = int(read_int())
    for _ in range(t):
        solution()
 
if __name__ == "__main__":
    main()