"""
Title: Medium Demon Problem (easy version)
Difficulty: 1700
Time: 25 min
URL: https://codeforces.com/contest/2044/problem/G1

This is the easy version of the problem. The key difference between the two versions is highlighted in bold.
A group of $n$ spiders has come together to exchange plushies. Initially, each spider has $1$ plushie. Every year, if spider $i$ has at least one plushie, he will give exactly one plushie to spider $r_i$. Otherwise, he will do nothing. Note that all plushie transfers happen at the same time. In this version, if any spider has more than $1$ plushie at any point in time, they will throw all but $1$ away.
The process is stable in the current year if each spider has the same number of plushies (before the current year's exchange) as he did the previous year (before the previous year's exchange). Note that year $1$ can never be stable.
Find the first year in which the process becomes stable.

Input
The first line contains an integer $t$ ($1 \leq t \leq 10^4$) — the number of test cases.
The first line of each test case contains an integer $n$ ($2 \leq n \leq 2 \cdot 10^5$) — the number of spiders.
The following line contains $n$ integers $r_1, r_2, \ldots, r_n$ ($1 \leq r_i \leq n, r_i \neq i$) — the recipient of the plushie of each spider.
It is guaranteed that the sum of $n$ over all test cases does not exceed $2 \cdot 10^5$.

Output
For each test case, output an integer on a new line, the first year in which the process becomes stable.

Example

5
2
2 1
5
2 3 4 5 1
5
2 1 4 2 3
5
4 1 1 5 4
10
4 3 9 1 6 7 9 10 10 3

2
2
5
4
5

Note
For the second test case:  
 At year $1$, the following array shows the number of plushies each spider has: $[1, 1, 1, 1, 1]$. Then, year $1$'s exchange happens. 
 At year $2$, the following array shows the number of plushies each spider has: $[1, 1, 1, 1, 1]$. Since this array is the same as the previous year, this year is stable. 
For the third test case:  
 At year $1$, the following array shows the number of plushies each spider has: $[1, 1, 1, 1, 1]$. Then, year $1$'s exchange happens. 
 At year $2$, the following array shows the number of plushies each spider has: $[1, 1, 1, 1, 0]$. Then, year $2$'s exchange happens. Note that even though two spiders gave spider $2$ plushies, spider $2$ may only keep one plushie. 
 At year $3$, the following array shows the number of plushies each spider has: $[1, 1, 0, 1, 0]$. Then, year $3$'s exchange happens. 
 At year $4$, the following array shows the number of plushies each spider has: $[1, 1, 0, 0, 0]$. Then, year $4$'s exchange happens. 
 At year $5$, the following array shows the number of plushies each spider has: $[1, 1, 0, 0, 0]$. Since this array is the same as the previous year, this year is stable.

Generated by CodeBridge
"""

import random, math, sys, heapq as heap
from itertools import accumulate
from math import ceil, sqrt, log, log2, floor, gcd, inf, isqrt, lcm
from collections import Counter, defaultdict, deque
from bisect import bisect_left, bisect_right
from random import randint
 
input = sys.stdin.readline
 
 
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
 
def rs():
    return input().strip()
 
 
def ri():
    return int(rs())
 
 
def rls(spliter=" "):
    return list(map(int, rs().split(spliter)))
 
 
def yn(res):
    print("YES" if res else "NO")
 
 
def acc(arr):
    return list(accumulate(arr))
 
 
rand = random.getrandbits(32)
 
 
def xor(x):
    return x ^ rand
 
 
# sys.setrecursionlimit(200000) # don't forget to use python 3
 
 
def solution(_):
    n = ri()
    nums = rls()
 
    adj = [[] for _ in range(n + 1)]
    indeg = [0] * (n + 1)
    
    for i in range(1, n + 1):
        adj[i].append(nums[i - 1])
        indeg[nums[i - 1]] += 1
 
    q = deque()
 
    for i in range(1, n + 1):
        if indeg[i] == 0:
            q.append(i)
 
    year = 2
    
    while q:
        year += 1
        
        for _ in range(len(q)):
            v = q.popleft()
 
            for nei in adj[v]:
                indeg[nei] -= 1
                if indeg[nei] == 0:
                    q.append(nei)
 
    print(year)
 
 
def main():
    t = 1
    t = ri()
    for _ in range(t):
        solution(_)
 
 
if __name__ == "__main__":
    main()