"""
Title: Coloring Game
Difficulty: 1300
Time: 60 min
URL: https://codeforces.com/contest/2112/problem/C

Alice and Bob are playing a game using an integer array $a$ of size $n$.
Initially, all elements of the array are colorless. First, Alice chooses $3$ elements and colors them red. Then Bob chooses any element and colors it blue (if it was red — recolor it). Alice wins if the sum of the red elements is strictly greater than the value of the blue element.
Your task is to calculate the number of ways that Alice can choose $3$ elements in order to win regardless of Bob's actions.

Input
The first line contains a single integer $t$ ($1 \le t \le 1000$) — the number of test cases.
The first line of each test case contains a single integer $n$ ($3 \le n \le 5000$).
The second line contains $n$ integers $a_1, a_2, \dots, a_n$ ($1 \le a_1 \le a_2 \le \cdots \le a_n \le 10^5$).
Additional constraint on the input: the sum of $n$ over all test cases doesn't exceed $5000$.

Output
For each test case, print a single integer — the number of ways that Alice can choose $3$ elements in order to win regardless of Bob's actions.

Example

6
3
1 2 3
4
1 1 2 4
5
7 7 7 7 7
5
1 1 2 2 4
6
2 3 3 4 5 5
5
1 1 1 1 3

0
0
10
2
16
0

Note
In the first two test cases, no matter which three elements Alice chooses, Bob will be able to paint one element blue so that Alice does not win.
In the third test case, Alice can choose any three elements. If Bob colors one of the red elements, the sum of red elements will be $14$, and the sum of blue elements will be $7$. If Bob chooses an uncolored element, the sum of red elements will be $21$, and the sum of blue elements will be $7$.
In the fourth test case, Alice can choose either the $1$-st, $3$-rd and $4$-th element, or the $2$-nd, $3$-rd and $4$-th element.

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
 
def solution(_):
    n = read_int()
    nums = read_list()
    
    nums.sort()
    
    maxx = nums[-1]
    
    count = 0
    
    for k in range(n - 1, 1, -1):
        j = k - 1
        i = 0
        while j > i:
            while i < j and nums[i] + nums[j] <= nums[k] or nums[i] + nums[j] + nums[k] <= maxx:
                i += 1
            
            if j > i:    
                count += (j - i)
                j -= 1
        
    print(count)
 
def main():
    t = 1
    t = int(read_int())
    for _ in range(t):
        solution(_)
 
if __name__ == "__main__":
    main()