"""
Title: Array Coloring
Difficulty: 800
Time: 10 min
URL: https://codeforces.com/problemset/problem/2191/A

You have  cards arranged in a row. The -th card has the integer  written on it. All integers are distinct.
You must color each card either  or  such that the following conditions are satisfied: 
 Any two adjacent cards in the row have different colors. 
 If you rearrange the cards so that the numbers on them are in increasing order, any two adjacent cards in the new row must also have different colors. 
Determine if such a coloring exists.

Input
Each test contains multiple test cases. The first line contains the number of test cases  (). The description of the test cases follows. 
The first line of each test case contains a single integer  () — the length of the array.
The second line of each test case contains  integers  ().
It is guaranteed that all elements of  are distinct.

Output
For each test case, output "YES" if you can color the cards so that the conditions are satisfied, and "NO" otherwise.
You can output the answer in any case (upper or lower). For example, the strings "yEs", "yes", "Yes", and "YES" will be recognized as positive responses. 

Example

4
4
2 3 4 1
3
2 3 1
5
3 4 1 2 5
5
3 1 4 2 5

YES
NO
YES
NO

Note
In the first example, the cards are colored as . After sorting, the cards become . Both sequences satisfy the condition, so the answer is YES.
In the second example, no valid coloring exists. For instance, if we color the cards as , the sorted sequence becomes . Here, the adjacent elements  and  have the same color, so the condition is not satisfied.
In the third example, a possible coloring is . After sorting, the cards become .

Generated by CodeBridge
"""

for _ in range(int(input())):
    n = int(input())
    nums = list(map(int, input().split()))

    for i in range(n - 1):
        if (nums[i] - nums[i + 1]) % 2 == 0:
            print("NO")
            break

    else:
        print("YES")
