"""
Title: DBMB and the Array
Difficulty: 800
Time: 5 min
URL: https://codeforces.com/contest/2193/problem/A

DBMB had a birthday yesterday. He was gifted an array $a$ of $n$ elements and a number $x$. But there is one problem: he only likes arrays where the sum of the elements equals $s$. To make the array appealing to him, you can perform the following operation any number of times:  
 Choose an index $i$ ($1 \le i \le n$) and add $x$ to the number $a_i$.  For example, if he was given the array $[1, 2, 3, 5]$ and $x = 2$, you can choose index $3$ and get the array $[1, 2, 5, 5]$. Your task is to determine whether the array can appeal to DBMB after any number of operations.

Input
Each test consists of several test cases. The first line contains a single integer $t$ ($1 \le t \le 1000$) — the number of test cases. The following describes the test cases.
The first line of each test case contains three integers $n$, $s$, $x$ ($1 \le n, x \le 10$, $1 \le s \le 100$).
The second line of each test case contains $n$ integers $a_1, a_2, \dots a_n$ ($1 \le a_i \le 10$) — the elements of the array gifted to DBMB.

Output
For each test case, output "YES" if the array can appeal to DBMB. Otherwise, output "NO".
You can output each letter in any case (lowercase or uppercase). For example, the strings "yEs", "yes", "Yes", and "YES" will be accepted as a positive answer.

Example

6
3 3 5
1 1 1
3 8 2
1 2 3
4 7 2
1 1 1 1
3 15 1
2 4 10
2 100 5
4 6
5 12 1
1 2 2 3 2

YES
YES
NO
NO
YES
YES

Note
In the second test case, $a = [1, 2, 3]$, applying the operation on $a_2$ gives us $a = [1, 4, 3]$. The sum of the array equals $s$.

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution():
    n, s, x = read_ints()
    total = sum(read_list())
    
    if total > s:
        print("NO")
        return
    
    yn((s - total) % x == 0)
 
 
 
 
 
 
 
 
 
 
def main():
    t = 1
    t = int(read_int())
    for _ in range(t):
        solution()
 
if __name__ == "__main__":
    main()