"""
Title: Segments with Small Set
Difficulty: Unknown
Time: 10 min
URL: https://codeforces.com/edu/course/2/lesson/9/2/practice/contest/307093/problem/E

Given an array of $n$ integers $a_i$. Let's say that a segment of this array $a[l..r]$ ($1\le l\le r\le n$) is good if there are no more than $k$ unique elements on this segment. Your task is to find the number of different good segments.

Input
The first line contains integers $n$ and $k$ ($1\le n\le 10^5$, $0\le k\le n$). The second line contains integers $a_i$ ($1\le a_i\le 10^5$).

Output
Print one integer, the number of good segments.

Example

7 3
2 6 4 3 6 8 3

20

Generated by CodeBridge
"""

from collections import Counter
 
n, k = list(map(int, input().split()))
nums = list(map(int, input().split()))
 
count = 0
 
window = Counter()
left = 0
 
for right in range(n):
    window[nums[right]] += 1
 
    while len(window) > k:
        window[nums[left]] -= 1
        
        if window[nums[left]] == 0:
            del window[nums[left]]
        
        left += 1
        
    count += (right - left + 1)
    
print(count)