"""
Title: Number of Smaller
Difficulty: Unknown
Time: 5 min
URL: https://codeforces.com/edu/course/2/lesson/9/1/practice/contest/307092/problem/B

You are given two arrays, sorted in non-decreasing order. For each element of the second array, find the number of elements in the first array strictly less than it.

Input
The first line contains integers $n$ and $m$, the sizes of the arrays ($1\le n, m\le 10^5$). The second line contains $n$ integers $a_i$, elements of the first array, the third line contains $m$ integers $b_i$, elements of the second array ($-10^9 \le a_i, b_i\le 10^9$).

Output
Print $m$ numbers, the number of elements of the first array less than each of the elements of the second array.

Example

6 7
1 6 9 13 18 18
2 3 8 13 15 21 25

1 1 2 3 4 6 6

Generated by CodeBridge
"""

n, m = list(map(int, input().split()))
a = list(map(int, input().split()))
b = list(map(int, input().split()))
 
i = 0
for j in range(m):
    while i < n and a[i] < b[j]:
        i += 1
        
    print(i, end=" ")
    
print()