"""
Title: Merging Arrays
Difficulty: Unknown
Time: 3 min
URL: https://codeforces.com/edu/course/2/lesson/9/1/practice/contest/307092/problem/A

For educational purposes, in the problems of this block, the time limit is large enough for the solution to pass in $O(n \log n)$ time, but try to write the solution in linear time, which we discussed in the lecture.
You are given two arrays, sorted in non-decreasing order. Merge them into one sorted array.

Input
The first line contains integers $n$ and $m$, the sizes of the arrays ($1\le n, m\le 10^5$). The second line contains $n$ integers $a_i$, elements of the first array, the third line contains $m$ integers $b_i$, elements of the second array ($-10^9 \le a_i, b_i\le 10^9$).

Output
Print $n + m$ integers, the merged array.

Example

6 7
1 6 9 13 18 18
2 3 8 13 15 21 25

1 2 3 6 8 9 13 13 15 18 18 21 25

Generated by CodeBridge
"""

n, m = list(map(int, input().split()))
 
arr1 = list(map(int, input().split()))
 
arr2 = list(map(int, input().split()))
result = []
i = j = 0
while i < n and j < m:
    if arr1[i] <= arr2[j]:
        result.append(arr1[i])
        i += 1
        
    else:
        result.append(arr2[j])
        j += 1
        
 
while i < n:
    result.append(arr1[i])
    i += 1    
    
while j < m:
    result.append(arr2[j])
    j += 1
    
print(*result)