"""
Title: Ilya and Queries
Difficulty: 1100
Time: 25 min
URL: https://codeforces.com/contest/313/problem/B

Ilya the Lion wants to help all his friends with passing exams. They need to solve the following problem to pass the IT exam.
You've got string s = s1s2... sn (n is the length of the string), consisting only of characters "." and "#" and m queries. Each query is described by a pair of integers li, ri (1 ≤ li < ri ≤ n). The answer to the query li, ri is the number of such integers i (li ≤ i < ri), that si = si + 1.
Ilya the Lion wants to help his friends but is there anyone to help him? Help Ilya, solve the problem.

Input
The first line contains string s of length n (2 ≤ n ≤ 105). It is guaranteed that the given string only consists of characters "." and "#".
The next line contains integer m (1 ≤ m ≤ 105) — the number of queries. Each of the next m lines contains the description of the corresponding query. The i-th line contains integers li, ri (1 ≤ li < ri ≤ n).

Output
Print m integers — the answers to the queries in the order in which they are given in the input.

Examples

......
4
3 4
2 3
1 6
2 6

1
1
5
4

#..###
5
1 3
5 6
1 5
3 6
3 4

1
1
2
2
0

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().strip().split())
def read_list(): return list(map(int, input().strip().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution():
    s = input().strip()
    m = read_int()
    n = len(s)
    
    prefix = [0] * (n + 1)
    
    for i in range(n-1):
        prefix[i + 1] = prefix[i]
        
        if s[i] == s[i+1]:
            prefix[i+1] += 1
    
    for _ in range(m):
        left, right = read_ints()
        left -= 1
        right -= 1
        
        print(prefix[right] - prefix[left])
 
 
 
 
def main():
    t = 1
    # t = int(read_int())
    for _ in range(t):
        solution()
 
if __name__ == "__main__":
    main()