"""
Title: Number of Equal
Difficulty: Unknown
Time: 2 min
URL: https://codeforces.com/edu/course/2/lesson/9/1/practice/contest/307092/problem/C

You are given two arrays $a$ and $b$, sorted in non-decreasing order. Find the number of pairs $(i, j)$ for which $a_i = b_j$.

Input
The first line contains integers $n$ and $m$, the sizes of the arrays ($1\le n, m\le 10^5$). The second line contains $n$ integers $a_i$, elements of the first array, the third line contains $m$ integers $b_i$, elements of the second array ($-10^9 \le a_i, b_i\le 10^9$).

Output
Print one number, the answer to the problem.

Example

8 7
1 1 3 3 3 5 8 8
1 3 3 4 5 5 5

11

Generated by CodeBridge
"""

from collections import Counter
 
n, m = list(map(int, input().split()))
a = list(map(int, input().split()))
b = list(map(int, input().split()))
 
 
countA = Counter(a)
countB = Counter(b)
 
total = 0
for num in countA:
    total += (countA[num] * countB[num])
    
print(total)