"""
Title: Segments with Small Spread
Difficulty: Unknown
Time: 30 min (with hint)
URL: https://codeforces.com/edu/course/2/lesson/9/2/practice/contest/307093/problem/F

Given an array of $n$ integers $a_i$. Let's say that a segment of this array $a[l..r]$ ($1\le l\le r\le n$) is good if the difference between the maximum and minimum elements on this segment is at most $k$. Your task is to find the number of different good segments.

Input
The first line contains integers $n$ and $k$ ($1\le n\le 10^5$, $0\le k\le 10^{18}$). The second line contains integers $a_i$ ($1\le a_i\le 10^{18}$).

Example

7 3
2 6 4 3 6 8 9

16

Generated by CodeBridge
"""

from collections import deque
 
n, k = list(map(int, input().split()))
nums = list(map(int, input().split()))
count = 0
 
maxDeque = deque()
minDeque = deque()
 
left = 0
for right in range(n):
    while maxDeque and nums[maxDeque[-1]] < nums[right]:
        maxDeque.pop()
    maxDeque.append(right)
        
    while minDeque and nums[minDeque[-1]] > nums[right]:
        minDeque.pop()
    minDeque.append(right)
    
    while maxDeque and minDeque and nums[maxDeque[0]] - nums[minDeque[0]] > k:
        if maxDeque[0] == left:
            maxDeque.popleft()
            
        if minDeque[0] == left:
            minDeque.popleft()
            
        left += 1
    
    count += (right - left + 1)
 
print(count)
 