"""
Title: Number of Segments with Big Sum
Difficulty: Unknown
Time: 5 min
URL: https://codeforces.com/edu/course/2/lesson/9/2/practice/contest/307093/problem/D

Given an array of $n$ integers $a_i$. Let's say that the segment of this array $a[l..r]$ ($1\le l\le r\le n$) is good if the sum of elements on this segment is at least $s$. Your task is to find the number of good segments.

Input
The first line contains integers $n$ and $s$ ($1\le n\le 10^5$, $1\le s\le 10^{18}$). The second line contains integers $a_i$ ($1\le a_i\le 10^9$).

Output
Print one integer, the number of good segments.

Example

7 20
2 6 4 3 6 8 9

9

Generated by CodeBridge
"""

import sys
input = sys.stdin.readline
 
def solve():
    n, s = map(int, input().split())
    nums = list(map(int, input().split()))
 
    count = 0
    
    window = 0
    left = 0
    for right in range(n):
        window += nums[right]
        
        while left <= right and window >= s:
            count += (n - right)
            window -= nums[left]
            left += 1
            
    print(count)
    return
 
t = 1
# t = int(input())
for _ in range(t):
    solve()