"""
Title: Segment with Big Sum
Difficulty: Unknown
Time: 15 min
Attempts: 3
URL: https://codeforces.com/edu/course/2/lesson/9/2/practice/contest/307093/problem/B

Given an array of $n$ integers $a_i$. Let's say that the segment of this array $a[l..r]$ ($1\le l\le r\le n$) is good if the sum of elements on this segment is at least $s$. Your task is to find the shortest good segment.

Input
The first line contains integers $n$ and $s$ ($1\le n\le 10^5$, $1\le s\le 10^{18}$). The second line contains integers $a_i$ ($1\le a_i\le 10^9$).

Output
Print one integer, the length of the shortest good segment. If there are no such segments, print $-1$.

Example

7 20
2 6 4 3 6 8 9

3

Generated by CodeBridge
"""

n, s = list(map(int, input().split()))
nums = list(map(int, input().split()))
 
shortest = float("inf")
 
cur_sum = 0
left = 0
 
for right in range(n):
    cur_sum += nums[right]
    
    while cur_sum >= s:
        shortest = min(shortest, right - left + 1)
        cur_sum -= nums[left]
        left += 1
        
print(shortest if shortest < float("inf") else -1)