"""
Title: Submission #362408924 - Codeforces
Difficulty: Unknown
Time: 30 min (with hint)
URL: https://codeforces.com/contest/863/submission/362408924

Problems

Submit Code

My Submissions

Status

Hacks

Standings

Custom Invocation

 

 

 

 

                General

 

 

    #
    Author
    Problem
    Lang
    Verdict
        Time
        Memory
    Sent
    Judged
         
     

    362408924

            Practice:

Bella_247    

        863D
         - 7

    PyPy 3-64

    Accepted

            921 ms

            28904 KB

    2026-02-11 17:17:19
    2026-02-11 17:17:19

        Compare

→ Source

Copy

def reverse_shift(index, l, r):
    if index == l:
        return r
    return index - 1
 
def reverse_reverse(index, l, r):
    return (l + r) - index

n, q, m = list(map(int, input().split()))
a = list(map(int, input().split()))
queries = [list(map(int, input().split())) for _ in range(q)]
b = list(map(int, input().split()))
 
 
for i in range(m):
    index = b[i]

    for t, l, r in reversed(queries):
        if t == 1 and l <= index <= r:
            index = reverse_shift(index, l, r)
        elif l <= index <= r:
            index = reverse_reverse(index, l, r)

    print(a[index - 1], end = " ")

?

Time: ? ms, memory: ? KB

Verdict: ?

Input

?

Participant's output

?

Jury's answer

?

Checker comment

?

Diagnostics

?

Click to see test details

                    Previous Submission:

              
              

                    Current Submission:

              
              

              
              

Add solution to problem

                    Filename:

                    Solution tag:

                                    Correct

                                    Incorrect

                                    Time limit exceeded

                                    Wrong answer

                                    Presentation error

                                    Memory limit exceeded

                                    Failed

Generated by CodeBridge
"""

def reverse_shift(index, l, r):
    if index == l:
        return r
    return index - 1
 
def reverse_reverse(index, l, r):
    return (l + r) - index
    
n, q, m = list(map(int, input().split()))
a = list(map(int, input().split()))
queries = [list(map(int, input().split())) for _ in range(q)]
b = list(map(int, input().split()))
 
 
for i in range(m):
    index = b[i]
    
    for t, l, r in reversed(queries):
        if t == 1 and l <= index <= r:
            index = reverse_shift(index, l, r)
        elif l <= index <= r:
            index = reverse_reverse(index, l, r)
            
    print(a[index - 1], end = " ")
    