"""
Title: Kuriyama Mirai's Stones
Difficulty: 1200
Time: 5 min
URL: https://codeforces.com/contest/433/problem/B

Kuriyama Mirai has killed many monsters and got many (namely n) stones. She numbers the stones from 1 to n. The cost of the i-th stone is vi. Kuriyama Mirai wants to know something about these stones so she will ask you two kinds of questions: 
 She will tell you two numbers, l and r (1 ≤ l ≤ r ≤ n), and you should tell her . 
 Let ui be the cost of the i-th cheapest stone (the cost that will be on the i-th place if we arrange all the stone costs in non-decreasing order). This time she will tell you two numbers, l and r (1 ≤ l ≤ r ≤ n), and you should tell her . 
For every question you should give the correct answer, or Kuriyama Mirai will say "fuyukai desu" and then become unhappy.

Input
The first line contains an integer n (1 ≤ n ≤ 105). The second line contains n integers: v1, v2, ..., vn (1 ≤ vi ≤ 109) — costs of the stones. 
The third line contains an integer m (1 ≤ m ≤ 105) — the number of Kuriyama Mirai's questions. Then follow m lines, each line contains three integers type, l and r (1 ≤ l ≤ r ≤ n; 1 ≤ type ≤ 2), describing a question. If type equal to 1, then you should output the answer for the first question, else you should output the answer for the second one.

Output
Print m lines. Each line must contain an integer — the answer to Kuriyama Mirai's question. Print the answers to the questions in the order of input.

Examples

6
6 4 2 7 2 7
3
2 3 6
1 3 4
1 1 6

24
9
28

4
5 5 2 3
10
1 2 4
2 1 4
1 1 1
2 1 4
2 1 2
1 1 1
1 3 3
1 1 3
1 4 4
1 2 2

10
15
5
15
5
5
2
12
3
5

Note
Please note that the answers to the questions may overflow 32-bit integer type.

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
 
input = sys.stdin.readline
def spaced(): return list(map(int, input().strip().split()))
def number(): return int(input().strip())
 
 
def solution():
    I = lambda x : int(x) - 1
    n = int(input().strip())
    nums = spaced()
    m = int(input().strip())
    
    sorted_nums = sorted(nums)
    nums.append(0)
    sorted_nums.append(0)
    
    for i in range(n):
        nums[i] += nums[i-1]
        sorted_nums[i] += sorted_nums[i-1]
        
    for _ in range(m):
        t, left, right = map(I, input().strip().split())
        
        if t == 0:
            print(nums[right] - nums[left - 1])
            
        else:
            print(sorted_nums[right] - sorted_nums[left -1])
            
    
    
    
 
t = 1
# t = int(input().strip())
for _ in range(t):
    solution()