"""
# Calculating Function

**Difficulty:** 800
**Tags:** implementation, math, 800
**URL:** https://codeforces.com/contest/486/problem/A

## Problem

For a positive integer n let's define a function f:
f(n) =  - 1 + 2 - 3 + .. + ( - 1)nn 
Your task is to calculate f(n) for a given integer n.

Input
The single line contains the positive integer n (1 ≤ n ≤ 1015).

Output
Print f(n) in a single line.

Examples

4

2

5

-3

Note
f(4) =  - 1 + 2 - 3 + 4 = 2
f(5) =  - 1 + 2 - 3 + 4 - 5 =  - 3

---
_Generated by CodeBridge_
"""

