"""
# Calculating Function

**Difficulty:** 800
**URL:** https://codeforces.com/contest/486/problem/A

## Problem

For a positive integer n let's define a function f:f(n) =  - 1 + 2 - 3 + .. + ( - 1)nn Your task is to calculate f(n) for a given integer n.InputThe single line contains the positive integer n (1 ≤ n ≤ 1015).OutputPrint f(n) in a single line.Examples425-3Notef(4) =  - 1 + 2 - 3 + 4 = 2f(5) =  - 1 + 2 - 3 + 4 - 5 =  - 3

---
_Generated by CodeBridge_
"""

