"""
Title: Chat Server's Outgoing Traffic
Difficulty: 1000
Time: 10 min
URL: https://codeforces.com/contest/5/problem/A

Polycarp is working on a new project called "Polychat". Following modern tendencies in IT, he decided, that this project should contain chat as well. To achieve this goal, Polycarp has spent several hours in front of his laptop and implemented a chat server that can process three types of commands: 
 Include a person to the chat ('Add' command). 
 Remove a person from the chat ('Remove' command). 
 Send a message from a person to all people, who are currently in the chat, including the one, who sends the message ('Send' command). 
Now Polycarp wants to find out the amount of outgoing traffic that the server will produce while processing a particular set of commands.
Polycarp knows that chat server sends no traffic for 'Add' and 'Remove' commands. When 'Send' command is processed, server sends l bytes to each participant of the chat, where l is the length of the message.
As Polycarp has no time, he is asking for your help in solving this problem.

Input
Input file will contain not more than 100 commands, each in its own line. No line will exceed 100 characters. Formats of the commands will be the following: 
 +<name> for 'Add' command. 
 -<name> for 'Remove' command. 
 <sender_name>:<message_text> for 'Send' command. 
<name> and <sender_name> is a non-empty sequence of Latin letters and digits. <message_text> can contain letters, digits and spaces, but can't start or end with a space. <message_text> can be an empty line.
It is guaranteed, that input data are correct, i.e. there will be no 'Add' command if person with such a name is already in the chat, there will be no 'Remove' command if there is no person with such a name in the chat etc.
All names are case-sensitive.

Output
Print a single number — answer to the problem.

Examples

+Mike
Mike:hello
+Kate
+Dmitry
-Dmitry
Kate:hi
-Kate

9

+Mike
-Mike
+Mike
Mike:Hi   I am here
-Mike
+Kate
-Kate

14

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution(_):
    commands = []
    
    while True:
        line = input().strip()
        if not line:
            break
        
        commands.append(line)
        
    people = set()
    total = 0
    
    for command in commands:
        if command[0] == "+":
            people.add(command[1:])
            
        elif command[0] == "-":
            people.remove(command[1:])
            
        else:
            total += len(people) * len(command.split(":")[1])
 
    print(total)
            
    
    
 
 
def main():
    t = 1
    # t = int(read_int())
    for _ in range(t):
        solution(_)
 
if __name__ == "__main__":
    main()