"""
Title: Longest Regular Bracket Sequence
Difficulty: 1900
Time: 60 min
Attempts: 2
URL: https://codeforces.com/contest/5/problem/C

This is yet another problem dealing with regular bracket sequences.
We should remind you that a bracket sequence is called regular, if by inserting «+» and «1» into it we can get a correct mathematical expression. For example, sequences «(())()», «()» and «(()(()))» are regular, while «)(», «(()» and «(()))(» are not. 
You are given a string of «(» and «)» characters. You are to find its longest substring that is a regular bracket sequence. You are to find the number of such substrings as well.

Input
The first line of the input file contains a non-empty string, consisting of «(» and «)» characters. Its length does not exceed 106.

Output
Print the length of the longest substring that is a regular bracket sequence, and the number of such substrings. If there are no such substrings, write the only line containing "0 1".

Examples

)((())))(()())

6 2

))(

0 1

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution(_):
    s = input().strip()
    
    stack = []
    good_brackets = []
    
    longest = 0
    
    for i, char in enumerate(s):
        if char == "(":
            stack.append(i)
            
        elif stack:
            opening_index = stack.pop()
            good_brackets.append([opening_index, i])
 
           
    if not good_brackets:
        print(0, 1)
        return
    
    good_brackets.sort()
    
    longest = 0
    count = 0
    
    win_start = 0
    last_end = float("-inf")
    # sample_end = last_end
 
    for start, end in good_brackets:
        if start < last_end:
            continue
        
        if start != last_end + 1:
            win_start = start
        
        length = end - win_start + 1
        
        if length > longest:
            count -= (count - 1)
            longest = length
            
        elif length == longest:
            count += 1
 
        last_end = end
    
    print(longest, count)
 
 
def main():
    t = 1
    # t = int(read_int())
    for _ in range(t):
        solution(_)
 
if __name__ == "__main__":
    main()