"""
Title: Center Alignment
Difficulty: 1200
Time: 30 min
URL: https://codeforces.com/contest/5/problem/B

Almost every text editor has a built-in function of center text alignment. The developers of the popular in Berland text editor «Textpad» decided to introduce this functionality into the fourth release of the product.
You are to implement the alignment in the shortest possible time. Good luck!

Input
The input file consists of one or more lines, each of the lines contains Latin letters, digits and/or spaces. The lines cannot start or end with a space. It is guaranteed that at least one of the lines has positive length. The length of each line and the total amount of the lines do not exceed 1000. 

Output
Format the given text, aligning it center. Frame the whole text with characters «*» of the minimum size. If a line cannot be aligned perfectly (for example, the line has even length, while the width of the block is uneven), you should place such lines rounding down the distance to the left or to the right edge and bringing them closer left or right alternatively (you should start with bringing left). Study the sample tests carefully to understand the output format better.

Examples

This  is

Codeforces
Beta
Round
5

************
* This  is *
*          *
*Codeforces*
*   Beta   *
*  Round   *
*     5    *
************

welcome to the
Codeforces
Beta
Round 5

and
good luck

****************
*welcome to the*
*  Codeforces  *
*     Beta     *
*   Round 5    *
*              *
*      and     *
*  good luck   *
****************

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import sys
import bisect
import itertools
 
input = sys.stdin.readline
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
def read_int(): return int(input().strip())
def read_ints(): return map(int, input().split())
def read_list(): return list(map(int, input().split()))
def yn(res): print("YES" if res else "NO")
 
inf = float('inf')
MOD = 10**9 + 7
def solution(_):
    lines = []
    max_len = 0
    
    for line in sys.stdin:
        line = line.strip()
        max_len = max(max_len, len(line))
        lines.append(line)
    
    alternating = 0
    
    print("*" * (max_len + 2))
    width = max_len
    
    for line in lines:
        line_len = len(line)
        
        left_space = (width - line_len) // 2
 
        if (width - line_len) % 2 != 0:
            left_space += alternating
            alternating ^= 1
        
        right_space = width - line_len - left_space
 
        print("*", end="")
        print(" " * left_space, end="")
        print(line, end="")
        print(" " * right_space, end="")
        print("*")
        
    print("*" * (max_len + 2))
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
def main():
    t = 1
    # t = int(read_int())
    for _ in range(t):
        solution(_)
 
if __name__ == "__main__":
    main()