"""
Title: Fox And Names
Difficulty: 1600
Time: 20 min
URL: https://codeforces.com/contest/510/problem/C

Fox Ciel is going to publish a paper on FOCS (Foxes Operated Computer Systems, pronounce: "Fox"). She heard a rumor: the authors list on the paper is always sorted in the lexicographical order. 
After checking some examples, she found out that sometimes it wasn't true. On some papers authors' names weren't sorted in lexicographical order in normal sense. But it was always true that after some modification of the order of letters in alphabet, the order of authors becomes lexicographical!
She wants to know, if there exists an order of letters in Latin alphabet such that the names on the paper she is submitting are following in the lexicographical order. If so, you should find out any such order.
Lexicographical order is defined in following way. When we compare s and t, first we find the leftmost position with differing characters: si ≠ ti. If there is no such position (i. e. s is a prefix of t or vice versa) the shortest string is less. Otherwise, we compare characters si and ti according to their order in alphabet.

Input
The first line contains an integer n (1 ≤ n ≤ 100): number of names.
Each of the following n lines contain one string namei (1 ≤ |namei| ≤ 100), the i-th name. Each name contains only lowercase Latin letters. All names are different.

Output
If there exists such order of letters that the given names are sorted lexicographically, output any such order as a permutation of characters 'a'–'z' (i. e. first output the first letter of the modified alphabet, then the second, and so on).
Otherwise output a single word "Impossible" (without quotes).

Examples

3
rivest
shamir
adleman

bcdefghijklmnopqrsatuvwxyz

10
tourist
petr
wjmzbmr
yeputons
vepifanov
scottwu
oooooooooooooooo
subscriber
rowdark
tankengineer

Impossible

10
petr
egor
endagorion
feferivan
ilovetanyaromanova
kostka
dmitriyh
maratsnowbear
bredorjaguarturnik
cgyforever

aghjlnopefikdmbcqrstuvwxyz

7
car
care
careful
carefully
becarefuldontforgetsomething
otherwiseyouwillbehacked
goodluck

acbdefhijklmnogpqrstuvwxyz

Generated by CodeBridge
"""

import random, math, sys, heapq as heap
from itertools import accumulate
from math import ceil, sqrt, log, log2, floor, gcd, inf, isqrt, lcm
from collections import Counter, defaultdict, deque
from bisect import bisect_left, bisect_right
from random import randint
 
input = sys.stdin.readline
 
 
def print(*args, **kwargs):
    sys.stdout.write(" ".join(map(str, args)) + kwargs.get("end", "\n"))
 
 
def rs():
    return input().strip()
 
 
def ri():
    return int(rs())
 
 
def rls(spliter=" "):
    return list(map(int, rs().split(spliter)))
 
 
def yn(res):
    print("YES" if res else "NO")
 
 
def acc(arr):
    return list(accumulate(arr))
 
 
rand = random.getrandbits(32)
 
 
def xor(x):
    return x ^ rand
 
 
# sys.setrecursionlimit(200000) # don't forget to use python 3
 
 
def compare(a, b):
    for i in range(min(len(a), len(b))):
        if a[i] != b[i]:
            return a[i], b[i]
 
    return (None, None) if len(a) > len(b) else ("", "")
 
 
def solution(_):
    n = ri()
    names = [rs() for _ in range(n)]
    adj = defaultdict(list)
    indegree = Counter()
 
    for i in range(n):
        seen = set()
 
        for j in range(i + 1, n):
            u, v = compare(names[i], names[j])
            if u is None:
                return print("Impossible")
 
            if v not in seen:
                adj[u].append(v)
                indegree[v] += 1
 
    q = deque()
 
    for c in "abcdefghijklmnopqrstuvwxyz":
        if indegree[c] == 0:
            q.append(c)
 
    result = []
    while q:
        c = q.popleft()
        result.append(c)
 
        for nei in adj[c]:
            indegree[nei] -= 1
 
            if indegree[nei] == 0:
                q.append(nei)
 
    print("".join(result) if len(result) == 26 else "Impossible")
 
 
def main():
    t = 1
    # t = ri()
    for _ in range(t):
        solution(_)
 
 
if __name__ == "__main__":
    main()