"""
Title: Longest k-Good Segment
Difficulty: 1600
Time: 5 min
URL: https://codeforces.com/contest/616/problem/D

The array a with n integers is given. Let's call the sequence of one or more consecutive elements in a segment. Also let's call the segment k-good if it contains no more than k different values.
Find any longest k-good segment.
As the input/output can reach huge size it is recommended to use fast input/output methods: for example, prefer to use scanf/printf instead of cin/cout in C++, prefer to use BufferedReader/PrintWriter instead of Scanner/System.out in Java.

Input
The first line contains two integers n, k (1 ≤ k ≤ n ≤ 5·105) — the number of elements in a and the parameter k.
The second line contains n integers ai (0 ≤ ai ≤ 106) — the elements of the array a.

Output
Print two integers l, r (1 ≤ l ≤ r ≤ n) — the index of the left and the index of the right ends of some k-good longest segment. If there are several longest segments you can print any of them. The elements in a are numbered from 1 to n from left to right.

Examples

5 5
1 2 3 4 5

1 5

9 3
6 5 1 2 3 2 1 4 5

3 7

3 1
1 2 3

1 1

Generated by CodeBridge
"""

from collections import defaultdict, deque, Counter
import math
import random
import sys
input = sys.stdin.readline
 
def solution():  
    n, k = map(int, input().split())
    nums = list(map(int, input().split()))
    
    longest = 0
    window = Counter()
    result = [1, 1]
    
    left = 0
    
    for right in range(n):
        window[nums[right]] += 1
        
        while len(window) > k:
            window[nums[left]] -= 1
            
            if window[nums[left]] == 0:
                del window[nums[left]]
                
            left += 1
            
        if right - left + 1 > longest:
            longest = right - left + 1
            result = [left + 1, right + 1]        
    
    print(*result)
    
    
t = 1
# t = int(input().strip())
for _ in range(t):
    solution()