"""
Title: Mirror Grid
Difficulty: Unknown
Time: 45 min
URL: https://codeforces.com/gym/671638/submission/363337109

You are given a square grid with $n$ rows and $n$ columns. Each cell contains either $0$ or $1$. 
In an operation, you can select a cell of the grid and flip it (from $0 \to 1$ or $1 \to 0$). Find the minimum number of operations you need to obtain a square that remains the same when rotated $0^{\circ}$, $90^{\circ}$, $180^{\circ}$ and $270^{\circ}$.
The picture below shows an example of all rotations of a grid.  

Input
The first line contains a single integer $t$ ($1 \leq t \leq 100$) — the number of test cases.
The first line of each test case contains a single integer $n$ ($1 \leq n \leq 100$) — the size of the grid.
Then $n$ lines follow, each with $n$ characters $a_{i,j}$ ($0 \leq a_{i,j} \leq 1$) — the number written in each cell.

Output
For each test case output a single integer  — the minimum number of operations needed to make the square look the same rotated $0^{\circ}$, $90^{\circ}$, $180^{\circ}$ and $270^{\circ}$.

Example

5
3
010
110
010
1
0
5
11100
11011
01011
10011
11000
5
01000
10101
01010
00010
01001
5
11001
00000
11111
10110
01111

1
0
9
7
6

Note
In the first test case, we can perform one operations to make the grid $\begin{matrix}0 & 1 & 0\\ 1 & 1 & \color{red}{1}\\ 0 & 1 & 0\end{matrix}$. Now, all rotations of the square are the same.
In the second test case, all rotations of the square are already the same, so we don't need any flips.

Generated by CodeBridge
"""

def mismatches(matrix, top, right, bottom, left):
    size = right - left + 1
 
    if size < 1:
        return 0
   
    top_side = [matrix[top][i] for i in range(left + 1, right)]
    right_side = [matrix[i][right] for i in range(top + 1, bottom)]
    bottom_side = [matrix[bottom][i] for i in range(right - 1, left, -1)]
    left_side = [matrix[i][left] for i in range(bottom - 1, top, -1)]
    
 
    summ = matrix[top][left] + matrix[top][right] + matrix[bottom][left] + matrix[bottom][right]
    
    count = (2 if summ == 2 else summ % 2)
   
    for i in range(size - 2):
        summ = top_side[i] + left_side[i] + bottom_side[i] + right_side[i]
        count += (2 if summ == 2 else summ % 2)
        
    return count + mismatches(matrix, top + 1,right - 1, bottom - 1, left + 1)
       
for _ in range(int(input())):
    n = int(input())
    grid = [list(map(int, list(input()))) for __ in range(n)]
        
    print(mismatches(grid, 0, n - 1, n - 1, 0))
    
    