"""
Title: Optimal Point on a Line
Difficulty: 1400
Time: 15 min
URL: https://codeforces.com/contest/710/submission/363649006

You are given n points on a line with their coordinates xi. Find the point x so the sum of distances to the given points is minimal.

Input
The first line contains integer n (1 ≤ n ≤ 3·105) — the number of points on the line.
The second line contains n integers xi ( - 109 ≤ xi ≤ 109) — the coordinates of the given n points.

Output
Print the only integer x — the position of the optimal point on the line. If there are several optimal points print the position of the leftmost one. It is guaranteed that the answer is always the integer.

Example

4
1 2 3 4

2

Generated by CodeBridge
"""

n = int(input())
 
nums = list(map(int, input().split()))
nums.sort()
index = (len(nums) - 1) // 2
 
print(nums[index])