"""
Title: Nested Segments
Difficulty: 1500
Time: 25 min
URL: https://codeforces.com/contest/976/submission/363634810

You are given a sequence a1, a2, ..., an of one-dimensional segments numbered 1 through n. Your task is to find two distinct indices i and j such that segment ai lies within segment aj.
Segment [l1, r1] lies within segment [l2, r2] iff l1 ≥ l2 and r1 ≤ r2.
Print indices i and j. If there are multiple answers, print any of them. If no answer exists, print -1 -1.

Input
The first line contains one integer n (1 ≤ n ≤ 3·105) — the number of segments.
Each of the next n lines contains two integers li and ri (1 ≤ li ≤ ri ≤ 109) — the i-th segment.

Output
Print two distinct indices i and j such that segment ai lies within segment aj. If there are multiple answers, print any of them. If no answer exists, print -1 -1.

Examples

5
1 10
2 9
3 9
2 3
2 9

2 1

3
1 5
2 6
6 20

-1 -1

Note
In the first example the following pairs are considered correct: 
 (2, 1), (3, 1), (4, 1), (5, 1) — not even touching borders; 
 (3, 2), (4, 2), (3, 5), (4, 5) — touch one border; 
 (5, 2), (2, 5) — match exactly.

Generated by CodeBridge
"""

def nestedSegments(n, segments):
 
    mapp = {}
 
    for i, segment in enumerate(segments):
        if segment in mapp:
            return i + 1, mapp[segment]
 
        mapp[segment] = i + 1
 
    segments.sort(key=lambda x: (x[0], -x[1]))
 
    for i in range(1, n):
        curr_segment = segments[i]
        prev_segment = segments[i - 1]
        
        if curr_segment[1] <= prev_segment[1]:
            return mapp[curr_segment], mapp[prev_segment]
 
    return -1, -1
 
n = int(input())
segments = [tuple(map(int, input().split())) for _ in range(n)]
 
print(*nestedSegments(n, segments))