"""
# List Comprehensions

**Difficulty:** Unknown
**Tags:** Prepare, Python, Basic Data Types
**URL:** https://www.hackerrank.com/challenges/list-comprehensions/submissions/code/462088869

---
_Generated by CodeBridge_
"""

if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    result = [
        [i,j,k]
        for i in range(x + 1)
        for j in range(y + 1)
        for k in range(z + 1)
        if i + j + k != n
    ]
    print(result)
